# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dlgBuildImport.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QGroupBox, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QWidget)
import PoB_rc

class Ui_BuildImport(object):
    def setupUi(self, BuildImport):
        if not BuildImport.objectName():
            BuildImport.setObjectName(u"BuildImport")
        BuildImport.resize(585, 490)
        BuildImport.setMaximumSize(QSize(585, 490))
        icon = QIcon()
        icon.addFile(u":/Art/Icons/paper-plane-return.png", QSize(), QIcon.Normal, QIcon.Off)
        BuildImport.setWindowIcon(icon)
        self.label_Import = QLabel(BuildImport)
        self.label_Import.setObjectName(u"label_Import")
        self.label_Import.setGeometry(QRect(20, 10, 141, 16))
        self.label_Status = QLabel(BuildImport)
        self.label_Status.setObjectName(u"label_Status")
        self.label_Status.setGeometry(QRect(170, 10, 401, 16))
        self.label_Info = QLabel(BuildImport)
        self.label_Info.setObjectName(u"label_Info")
        self.label_Info.setGeometry(QRect(20, 30, 551, 40))
        self.label_Info.setWordWrap(True)
        self.label_Info.setOpenExternalLinks(True)
        self.label_Info.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse)
        self.combo_Realm = QComboBox(BuildImport)
        self.combo_Realm.addItem(u"PC")
        self.combo_Realm.addItem(u"Xbox")
        self.combo_Realm.addItem(u"PS4")
        self.combo_Realm.addItem(u"Garena")
        self.combo_Realm.addItem(u"Tencent")
        self.combo_Realm.setObjectName(u"combo_Realm")
        self.combo_Realm.setGeometry(QRect(20, 80, 70, 24))
        self.combo_Account_History = QComboBox(BuildImport)
        self.combo_Account_History.addItem("")
        self.combo_Account_History.setObjectName(u"combo_Account_History")
        self.combo_Account_History.setGeometry(QRect(410, 80, 160, 24))
        self.lineedit_Account = QLineEdit(BuildImport)
        self.lineedit_Account.setObjectName(u"lineedit_Account")
        self.lineedit_Account.setGeometry(QRect(100, 80, 201, 24))
        self.btn_StartImport = QPushButton(BuildImport)
        self.btn_StartImport.setObjectName(u"btn_StartImport")
        self.btn_StartImport.setGeometry(QRect(320, 80, 75, 24))
        self.grpbox_CharImport = QGroupBox(BuildImport)
        self.grpbox_CharImport.setObjectName(u"grpbox_CharImport")
        self.grpbox_CharImport.setEnabled(False)
        self.grpbox_CharImport.setGeometry(QRect(20, 120, 551, 201))
        self.label_League = QLabel(self.grpbox_CharImport)
        self.label_League.setObjectName(u"label_League")
        self.label_League.setGeometry(QRect(10, 32, 70, 16))
        self.label_League.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.combo_League = QComboBox(self.grpbox_CharImport)
        self.combo_League.addItem("")
        self.combo_League.setObjectName(u"combo_League")
        self.combo_League.setGeometry(QRect(85, 30, 251, 22))
        self.combo_League.setMaxVisibleItems(15)
        self.combo_CharList = QComboBox(self.grpbox_CharImport)
        self.combo_CharList.addItem("")
        self.combo_CharList.setObjectName(u"combo_CharList")
        self.combo_CharList.setGeometry(QRect(85, 60, 455, 22))
        font = QFont()
        font.setFamilies([u"Noto Mono"])
        self.combo_CharList.setFont(font)
        self.btn_TreeJewels = QPushButton(self.grpbox_CharImport)
        self.btn_TreeJewels.setObjectName(u"btn_TreeJewels")
        self.btn_TreeJewels.setGeometry(QRect(105, 120, 200, 24))
        self.btn_Items = QPushButton(self.grpbox_CharImport)
        self.btn_Items.setObjectName(u"btn_Items")
        self.btn_Items.setGeometry(QRect(320, 120, 100, 24))
        self.check_DeleteJewels = QCheckBox(self.grpbox_CharImport)
        self.check_DeleteJewels.setObjectName(u"check_DeleteJewels")
        self.check_DeleteJewels.setGeometry(QRect(210, 90, 60, 20))
        self.check_DeleteJewels.setChecked(True)
        self.check_DeleteItems = QCheckBox(self.grpbox_CharImport)
        self.check_DeleteItems.setObjectName(u"check_DeleteItems")
        self.check_DeleteItems.setGeometry(QRect(300, 90, 60, 20))
        self.check_DeleteItems.setChecked(True)
        self.check_DeleteSkills = QCheckBox(self.grpbox_CharImport)
        self.check_DeleteSkills.setObjectName(u"check_DeleteSkills")
        self.check_DeleteSkills.setGeometry(QRect(390, 90, 60, 20))
        self.check_DeleteSkills.setChecked(True)
        self.label_Info_2 = QLabel(self.grpbox_CharImport)
        self.label_Info_2.setObjectName(u"label_Info_2")
        self.label_Info_2.setGeometry(QRect(20, 170, 500, 20))
        self.label_Info_2.setWordWrap(True)
        self.btn_ImportAll = QPushButton(self.grpbox_CharImport)
        self.btn_ImportAll.setObjectName(u"btn_ImportAll")
        self.btn_ImportAll.setGeometry(QRect(10, 120, 80, 24))
        self.label_Characters = QLabel(self.grpbox_CharImport)
        self.label_Characters.setObjectName(u"label_Characters")
        self.label_Characters.setGeometry(QRect(10, 62, 70, 16))
        self.label_Characters.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_Skills = QPushButton(self.grpbox_CharImport)
        self.btn_Skills.setObjectName(u"btn_Skills")
        self.btn_Skills.setGeometry(QRect(440, 120, 100, 24))
        self.combo_Import = QComboBox(self.grpbox_CharImport)
        self.combo_Import.addItem("")
        self.combo_Import.addItem("")
        self.combo_Import.setObjectName(u"combo_Import")
        self.combo_Import.setGeometry(QRect(380, 30, 160, 22))
        self.label = QLabel(self.grpbox_CharImport)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 91, 16))
        self.check_DeleteTrees = QCheckBox(self.grpbox_CharImport)
        self.check_DeleteTrees.setObjectName(u"check_DeleteTrees")
        self.check_DeleteTrees.setGeometry(QRect(120, 90, 60, 20))
        self.check_DeleteTrees.setChecked(True)
        self.grpbox_BuildSharing = QGroupBox(BuildImport)
        self.grpbox_BuildSharing.setObjectName(u"grpbox_BuildSharing")
        self.grpbox_BuildSharing.setGeometry(QRect(20, 340, 551, 91))
        self.label_BuildShare = QLabel(self.grpbox_BuildSharing)
        self.label_BuildShare.setObjectName(u"label_BuildShare")
        self.label_BuildShare.setGeometry(QRect(10, 25, 241, 16))
        self.lineedit_BuildShare = QLineEdit(self.grpbox_BuildSharing)
        self.lineedit_BuildShare.setObjectName(u"lineedit_BuildShare")
        self.lineedit_BuildShare.setGeometry(QRect(10, 50, 431, 24))
        self.btn_ImportBuildSharing = QPushButton(self.grpbox_BuildSharing)
        self.btn_ImportBuildSharing.setObjectName(u"btn_ImportBuildSharing")
        self.btn_ImportBuildSharing.setEnabled(False)
        self.btn_ImportBuildSharing.setGeometry(QRect(460, 50, 75, 24))
        self.btn_Close = QPushButton(BuildImport)
        self.btn_Close.setObjectName(u"btn_Close")
        self.btn_Close.setGeometry(QRect(500, 450, 70, 24))
#if QT_CONFIG(shortcut)
        self.label_League.setBuddy(self.combo_League)
        self.label_Characters.setBuddy(self.combo_CharList)
        self.label.setBuddy(self.check_DeleteTrees)
        self.label_BuildShare.setBuddy(self.lineedit_BuildShare)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.lineedit_BuildShare, self.btn_ImportBuildSharing)
        QWidget.setTabOrder(self.btn_ImportBuildSharing, self.btn_Close)
        QWidget.setTabOrder(self.btn_Close, self.combo_Realm)
        QWidget.setTabOrder(self.combo_Realm, self.lineedit_Account)
        QWidget.setTabOrder(self.lineedit_Account, self.btn_StartImport)
        QWidget.setTabOrder(self.btn_StartImport, self.combo_Account_History)
        QWidget.setTabOrder(self.combo_Account_History, self.combo_League)
        QWidget.setTabOrder(self.combo_League, self.combo_Import)
        QWidget.setTabOrder(self.combo_Import, self.combo_CharList)
        QWidget.setTabOrder(self.combo_CharList, self.check_DeleteTrees)
        QWidget.setTabOrder(self.check_DeleteTrees, self.check_DeleteJewels)
        QWidget.setTabOrder(self.check_DeleteJewels, self.check_DeleteItems)
        QWidget.setTabOrder(self.check_DeleteItems, self.check_DeleteSkills)
        QWidget.setTabOrder(self.check_DeleteSkills, self.btn_ImportAll)
        QWidget.setTabOrder(self.btn_ImportAll, self.btn_TreeJewels)
        QWidget.setTabOrder(self.btn_TreeJewels, self.btn_Items)
        QWidget.setTabOrder(self.btn_Items, self.btn_Skills)

        self.retranslateUi(BuildImport)

        self.combo_Import.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(BuildImport)
    # setupUi

    def retranslateUi(self, BuildImport):
        BuildImport.setWindowTitle(QCoreApplication.translate("BuildImport", u"Character Import", None))
        self.label_Import.setText(QCoreApplication.translate("BuildImport", u"Character Import Status :", None))
        self.label_Status.setText(QCoreApplication.translate("BuildImport", u"Idle", None))
        self.label_Info.setText(QCoreApplication.translate("BuildImport", u"To start importing a character, enter the character's account name. Note: if the account name contains non-ASCII characters then it will be URL encoded on the fly.", None))

        self.combo_Account_History.setItemText(0, QCoreApplication.translate("BuildImport", u"Account List", None))

        self.lineedit_Account.setPlaceholderText(QCoreApplication.translate("BuildImport", u"Type Character Name Here", None))
        self.btn_StartImport.setText(QCoreApplication.translate("BuildImport", u"&Start", None))
        self.grpbox_CharImport.setTitle(QCoreApplication.translate("BuildImport", u"Choose character to import data from:", None))
        self.label_League.setText(QCoreApplication.translate("BuildImport", u"&League: ", None))
        self.combo_League.setItemText(0, QCoreApplication.translate("BuildImport", u"All", None))

        self.combo_CharList.setItemText(0, QCoreApplication.translate("BuildImport", u"Character List", None))

        self.btn_TreeJewels.setText(QCoreApplication.translate("BuildImport", u"Import &Passive Tree and Jewels", None))
        self.btn_Items.setText(QCoreApplication.translate("BuildImport", u"Import Ite&ms", None))
        self.check_DeleteJewels.setText(QCoreApplication.translate("BuildImport", u"&Jewels", None))
        self.check_DeleteItems.setText(QCoreApplication.translate("BuildImport", u"Items", None))
        self.check_DeleteSkills.setText(QCoreApplication.translate("BuildImport", u"Skills", None))
        self.label_Info_2.setText(QCoreApplication.translate("BuildImport", u"TIP: Remember to update the bandit choice as this cannot be imported", None))
        self.btn_ImportAll.setText(QCoreApplication.translate("BuildImport", u"&Import All", None))
        self.label_Characters.setText(QCoreApplication.translate("BuildImport", u"C&haracters:", None))
        self.btn_Skills.setText(QCoreApplication.translate("BuildImport", u"Import S&kills", None))
        self.combo_Import.setItemText(0, QCoreApplication.translate("BuildImport", u"Import to this build", None))
        self.combo_Import.setItemText(1, QCoreApplication.translate("BuildImport", u"Import to a new build", None))

        self.label.setText(QCoreApplication.translate("BuildImport", u"Delete e&xisting :", None))
        self.check_DeleteTrees.setText(QCoreApplication.translate("BuildImport", u"&Trees", None))
        self.grpbox_BuildSharing.setTitle(QCoreApplication.translate("BuildImport", u"Build Sharing", None))
        self.label_BuildShare.setText(QCoreApplication.translate("BuildImport", u"To import a build, enter &URL or code here:", None))
        self.lineedit_BuildShare.setText("")
        self.lineedit_BuildShare.setPlaceholderText(QCoreApplication.translate("BuildImport", u"Paste Import URL here", None))
        self.btn_ImportBuildSharing.setText(QCoreApplication.translate("BuildImport", u"&Import", None))
        self.btn_Close.setText(QCoreApplication.translate("BuildImport", u"&Close", None))
    # retranslateUi

