# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dlgSettings.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QComboBox,
    QDialog, QDialogButtonBox, QGroupBox, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QSlider,
    QSpinBox, QWidget)
import PoB_rc

class Ui_Settings(object):
    def setupUi(self, Settings):
        if not Settings.objectName():
            Settings.setObjectName(u"Settings")
        Settings.setWindowModality(Qt.ApplicationModal)
        Settings.resize(400, 550)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMaximumSize(QSize(400, 550))
        icon = QIcon()
        icon.addFile(u":/Art/Icons/construction.png", QSize(), QIcon.Normal, QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setModal(True)
        self.btnBox = QDialogButtonBox(Settings)
        self.btnBox.setObjectName(u"btnBox")
        self.btnBox.setGeometry(QRect(20, 510, 341, 32))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.btnBox.sizePolicy().hasHeightForWidth())
        self.btnBox.setSizePolicy(sizePolicy1)
        self.btnBox.setOrientation(Qt.Horizontal)
        self.btnBox.setStandardButtons(QDialogButtonBox.Discard|QDialogButtonBox.Reset|QDialogButtonBox.RestoreDefaults|QDialogButtonBox.Save)
        self.btnBox.setCenterButtons(True)
        self.groupBox = QGroupBox(Settings)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 380, 271))
        self.label_Protocol = QLabel(self.groupBox)
        self.label_Protocol.setObjectName(u"label_Protocol")
        self.label_Protocol.setGeometry(QRect(0, 22, 120, 16))
        self.label_Protocol.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_Proxy = QLabel(self.groupBox)
        self.label_Proxy.setObjectName(u"label_Proxy")
        self.label_Proxy.setGeometry(QRect(0, 52, 120, 16))
        self.label_Proxy.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_BuildPath = QLabel(self.groupBox)
        self.label_BuildPath.setObjectName(u"label_BuildPath")
        self.label_BuildPath.setGeometry(QRect(0, 82, 120, 16))
        self.label_BuildPath.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_NP_Colours = QLabel(self.groupBox)
        self.label_NP_Colours.setObjectName(u"label_NP_Colours")
        self.label_NP_Colours.setGeometry(QRect(10, 112, 195, 16))
        self.label_NP_Colours.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.combo_Proxy = QComboBox(self.groupBox)
        self.combo_Proxy.addItem("")
        self.combo_Proxy.addItem("")
        self.combo_Proxy.addItem("")
        self.combo_Proxy.addItem("")
        self.combo_Proxy.addItem("")
        self.combo_Proxy.setObjectName(u"combo_Proxy")
        self.combo_Proxy.setGeometry(QRect(130, 49, 90, 24))
        self.combo_Protocol = QComboBox(self.groupBox)
        self.combo_Protocol.addItem("")
        self.combo_Protocol.addItem("")
        self.combo_Protocol.addItem("")
        self.combo_Protocol.setObjectName(u"combo_Protocol")
        self.combo_Protocol.setGeometry(QRect(130, 18, 69, 26))
        self.combo_NP_Colours = QComboBox(self.groupBox)
        self.combo_NP_Colours.addItem("")
        self.combo_NP_Colours.addItem("")
        self.combo_NP_Colours.addItem("")
        self.combo_NP_Colours.setObjectName(u"combo_NP_Colours")
        self.combo_NP_Colours.setGeometry(QRect(210, 108, 125, 26))
        self.lineedit_BuildPath = QLineEdit(self.groupBox)
        self.lineedit_BuildPath.setObjectName(u"lineedit_BuildPath")
        self.lineedit_BuildPath.setGeometry(QRect(130, 80, 205, 22))
        self.check_Beta = QCheckBox(self.groupBox)
        self.check_Beta.setObjectName(u"check_Beta")
        self.check_Beta.setEnabled(False)
        self.check_Beta.setGeometry(QRect(20, 230, 204, 20))
        self.check_Beta.setLayoutDirection(Qt.RightToLeft)
        self.lineedit_Proxy = QLineEdit(self.groupBox)
        self.lineedit_Proxy.setObjectName(u"lineedit_Proxy")
        self.lineedit_Proxy.setGeometry(QRect(220, 50, 155, 22))
        self.btn_BuildPath = QPushButton(self.groupBox)
        self.btn_BuildPath.setObjectName(u"btn_BuildPath")
        self.btn_BuildPath.setGeometry(QRect(340, 79, 30, 24))
        self.label_Pos_Colour = QLabel(self.groupBox)
        self.label_Pos_Colour.setObjectName(u"label_Pos_Colour")
        self.label_Pos_Colour.setGeometry(QRect(10, 142, 195, 16))
        self.label_Pos_Colour.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_Neg_Colour = QLabel(self.groupBox)
        self.label_Neg_Colour.setObjectName(u"label_Neg_Colour")
        self.label_Neg_Colour.setGeometry(QRect(10, 172, 195, 16))
        self.label_Neg_Colour.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_HL_Colour = QLabel(self.groupBox)
        self.label_HL_Colour.setObjectName(u"label_HL_Colour")
        self.label_HL_Colour.setGeometry(QRect(10, 202, 195, 16))
        self.label_HL_Colour.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineedit_Pos_Colour = QLineEdit(self.groupBox)
        self.lineedit_Pos_Colour.setObjectName(u"lineedit_Pos_Colour")
        self.lineedit_Pos_Colour.setGeometry(QRect(210, 140, 125, 22))
        self.lineedit_Neg_Colour = QLineEdit(self.groupBox)
        self.lineedit_Neg_Colour.setObjectName(u"lineedit_Neg_Colour")
        self.lineedit_Neg_Colour.setGeometry(QRect(210, 170, 125, 22))
        self.lineedit_HL_Colour = QLineEdit(self.groupBox)
        self.lineedit_HL_Colour.setObjectName(u"lineedit_HL_Colour")
        self.lineedit_HL_Colour.setGeometry(QRect(210, 200, 125, 22))
        self.btn_Pos_Colour = QPushButton(self.groupBox)
        self.btn_Pos_Colour.setObjectName(u"btn_Pos_Colour")
        self.btn_Pos_Colour.setGeometry(QRect(340, 140, 30, 24))
        self.btn_Neg_Colour = QPushButton(self.groupBox)
        self.btn_Neg_Colour.setObjectName(u"btn_Neg_Colour")
        self.btn_Neg_Colour.setGeometry(QRect(340, 170, 30, 24))
        self.btn_HL_Colour = QPushButton(self.groupBox)
        self.btn_HL_Colour.setObjectName(u"btn_HL_Colour")
        self.btn_HL_Colour.setGeometry(QRect(340, 200, 30, 24))
        self.groupBox_2 = QGroupBox(Settings)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 290, 380, 200))
        self.check_ShowBuildName = QCheckBox(self.groupBox_2)
        self.check_ShowBuildName.setObjectName(u"check_ShowBuildName")
        self.check_ShowBuildName.setEnabled(True)
        self.check_ShowBuildName.setGeometry(QRect(20, 20, 245, 20))
        self.check_ShowBuildName.setLayoutDirection(Qt.RightToLeft)
        self.check_ShowThousandsSeparators = QCheckBox(self.groupBox_2)
        self.check_ShowThousandsSeparators.setObjectName(u"check_ShowThousandsSeparators")
        self.check_ShowThousandsSeparators.setEnabled(True)
        self.check_ShowThousandsSeparators.setGeometry(QRect(20, 40, 245, 20))
        self.check_ShowThousandsSeparators.setLayoutDirection(Qt.RightToLeft)
        self.label_GemQuality = QLabel(self.groupBox_2)
        self.label_GemQuality.setObjectName(u"label_GemQuality")
        self.label_GemQuality.setGeometry(QRect(81, 112, 165, 16))
        self.label_GemQuality.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_Level = QLabel(self.groupBox_2)
        self.label_Level.setObjectName(u"label_Level")
        self.label_Level.setGeometry(QRect(81, 142, 165, 16))
        self.label_Level.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.check_Tooltips = QCheckBox(self.groupBox_2)
        self.check_Tooltips.setObjectName(u"check_Tooltips")
        self.check_Tooltips.setEnabled(True)
        self.check_Tooltips.setGeometry(QRect(20, 80, 245, 20))
        self.check_Tooltips.setLayoutDirection(Qt.RightToLeft)
        self.check_BuildWarnings = QCheckBox(self.groupBox_2)
        self.check_BuildWarnings.setObjectName(u"check_BuildWarnings")
        self.check_BuildWarnings.setEnabled(True)
        self.check_BuildWarnings.setGeometry(QRect(20, 60, 245, 20))
        self.check_BuildWarnings.setLayoutDirection(Qt.RightToLeft)
        self.label_AffixQuality = QLabel(self.groupBox_2)
        self.label_AffixQuality.setObjectName(u"label_AffixQuality")
        self.label_AffixQuality.setGeometry(QRect(6, 172, 150, 16))
        self.label_AffixQuality.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.spin_GemQuality = QSpinBox(self.groupBox_2)
        self.spin_GemQuality.setObjectName(u"spin_GemQuality")
        self.spin_GemQuality.setGeometry(QRect(253, 110, 42, 22))
        self.spin_GemQuality.setMaximum(30)
        self.spin_Level = QSpinBox(self.groupBox_2)
        self.spin_Level.setObjectName(u"spin_Level")
        self.spin_Level.setGeometry(QRect(253, 140, 42, 22))
        self.spin_Level.setMinimum(1)
        self.spin_Level.setMaximum(100)
        self.slider_AffixQuality = QSlider(self.groupBox_2)
        self.slider_AffixQuality.setObjectName(u"slider_AffixQuality")
        self.slider_AffixQuality.setGeometry(QRect(170, 170, 161, 22))
        self.slider_AffixQuality.setMaximum(100)
        self.slider_AffixQuality.setValue(50)
        self.slider_AffixQuality.setOrientation(Qt.Horizontal)
        self.label_AffixQValue = QLabel(self.groupBox_2)
        self.label_AffixQValue.setObjectName(u"label_AffixQValue")
        self.label_AffixQValue.setGeometry(QRect(340, 172, 30, 16))
        self.label_AffixQValue.setAlignment(Qt.AlignCenter)
        self.label_ThousandsSeparator = QLabel(self.groupBox_2)
        self.label_ThousandsSeparator.setObjectName(u"label_ThousandsSeparator")
        self.label_ThousandsSeparator.setGeometry(QRect(285, 40, 80, 16))
#if QT_CONFIG(shortcut)
        self.label_Protocol.setBuddy(self.combo_Protocol)
        self.label_Proxy.setBuddy(self.combo_Proxy)
        self.label_BuildPath.setBuddy(self.lineedit_BuildPath)
        self.label_NP_Colours.setBuddy(self.combo_NP_Colours)
        self.label_Pos_Colour.setBuddy(self.combo_NP_Colours)
        self.label_Neg_Colour.setBuddy(self.combo_NP_Colours)
        self.label_HL_Colour.setBuddy(self.combo_NP_Colours)
        self.label_GemQuality.setBuddy(self.spin_GemQuality)
        self.label_Level.setBuddy(self.spin_Level)
        self.label_AffixQuality.setBuddy(self.slider_AffixQuality)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.combo_Protocol, self.combo_Proxy)
        QWidget.setTabOrder(self.combo_Proxy, self.lineedit_Proxy)
        QWidget.setTabOrder(self.lineedit_Proxy, self.lineedit_BuildPath)
        QWidget.setTabOrder(self.lineedit_BuildPath, self.btn_BuildPath)
        QWidget.setTabOrder(self.btn_BuildPath, self.combo_NP_Colours)
        QWidget.setTabOrder(self.combo_NP_Colours, self.check_Beta)
        QWidget.setTabOrder(self.check_Beta, self.check_ShowBuildName)
        QWidget.setTabOrder(self.check_ShowBuildName, self.check_ShowThousandsSeparators)
        QWidget.setTabOrder(self.check_ShowThousandsSeparators, self.spin_GemQuality)
        QWidget.setTabOrder(self.spin_GemQuality, self.spin_Level)
        QWidget.setTabOrder(self.spin_Level, self.slider_AffixQuality)
        QWidget.setTabOrder(self.slider_AffixQuality, self.check_BuildWarnings)
        QWidget.setTabOrder(self.check_BuildWarnings, self.check_Tooltips)

        self.retranslateUi(Settings)
        self.btnBox.accepted.connect(Settings.accept)
        self.btnBox.rejected.connect(Settings.reject)

        QMetaObject.connectSlotsByName(Settings)
    # setupUi

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QCoreApplication.translate("Settings", u"Settings", None))
        self.groupBox.setTitle(QCoreApplication.translate("Settings", u"Application", None))
        self.label_Protocol.setText(QCoreApplication.translate("Settings", u"Connection Protocol:", None))
        self.label_Proxy.setText(QCoreApplication.translate("Settings", u"Proxy Server:", None))
        self.label_BuildPath.setText(QCoreApplication.translate("Settings", u"Build save path:", None))
        self.label_NP_Colours.setText(QCoreApplication.translate("Settings", u"Node Power colours:", None))
        self.combo_Proxy.setItemText(0, QCoreApplication.translate("Settings", u"None", None))
        self.combo_Proxy.setItemText(1, QCoreApplication.translate("Settings", u"HTTPS", None))
        self.combo_Proxy.setItemText(2, QCoreApplication.translate("Settings", u"HTTP", None))
        self.combo_Proxy.setItemText(3, QCoreApplication.translate("Settings", u"SOCKS5", None))
        self.combo_Proxy.setItemText(4, QCoreApplication.translate("Settings", u"SOCKS5H", None))

        self.combo_Protocol.setItemText(0, QCoreApplication.translate("Settings", u"Auto", None))
        self.combo_Protocol.setItemText(1, QCoreApplication.translate("Settings", u"IPv4", None))
        self.combo_Protocol.setItemText(2, QCoreApplication.translate("Settings", u"IPv6", None))

        self.combo_NP_Colours.setItemText(0, QCoreApplication.translate("Settings", u"Red & Blue", None))
        self.combo_NP_Colours.setItemText(1, QCoreApplication.translate("Settings", u"Red & Green", None))
        self.combo_NP_Colours.setItemText(2, QCoreApplication.translate("Settings", u"Green & Blue", None))

        self.check_Beta.setText(QCoreApplication.translate("Settings", u"Opt in to weekly test builds:", None))
        self.btn_BuildPath.setText(QCoreApplication.translate("Settings", u"...", None))
        self.label_Pos_Colour.setText(QCoreApplication.translate("Settings", u"Hex colour for Positive values:", None))
        self.label_Neg_Colour.setText(QCoreApplication.translate("Settings", u"Hex colour for Negative values:", None))
        self.label_HL_Colour.setText(QCoreApplication.translate("Settings", u"Hex colour to Highlight nodes:", None))
        self.btn_Pos_Colour.setText(QCoreApplication.translate("Settings", u"...", None))
        self.btn_Neg_Colour.setText(QCoreApplication.translate("Settings", u"...", None))
        self.btn_HL_Colour.setText(QCoreApplication.translate("Settings", u"...", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Settings", u"Build related", None))
        self.check_ShowBuildName.setText(QCoreApplication.translate("Settings", u"Show build name in window title", None))
        self.check_ShowThousandsSeparators.setText(QCoreApplication.translate("Settings", u"Show thousands separators", None))
        self.label_GemQuality.setText(QCoreApplication.translate("Settings", u"Default gem quality:", None))
        self.label_Level.setText(QCoreApplication.translate("Settings", u"Default character level:", None))
        self.check_Tooltips.setText(QCoreApplication.translate("Settings", u"Show tooltips only for affected slots", None))
        self.check_BuildWarnings.setText(QCoreApplication.translate("Settings", u"Show build warnings", None))
        self.label_AffixQuality.setText(QCoreApplication.translate("Settings", u"Default item affix quality", None))
        self.label_AffixQValue.setText(QCoreApplication.translate("Settings", u"nn", None))
#if QT_CONFIG(tooltip)
        self.label_ThousandsSeparator.setToolTip(QCoreApplication.translate("Settings", u"Thousands and Decimal separators for your locale", None))
#endif // QT_CONFIG(tooltip)
        self.label_ThousandsSeparator.setText(QCoreApplication.translate("Settings", u"Sep", None))
    # retranslateUi

