# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PoB_Main_Window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QFontComboBox, QFrame, QGraphicsView, QGridLayout,
    QGroupBox, QHBoxLayout, QLabel, QLineEdit,
    QListView, QListWidget, QListWidgetItem, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QScrollArea, QSizePolicy, QSpacerItem, QSpinBox,
    QSplitter, QStatusBar, QTabWidget, QTextEdit,
    QToolBar, QVBoxLayout, QWidget)

from widgets.listbox import ListBox
import PoB_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1421, 861)
        MainWindow.setMinimumSize(QSize(800, 600))
        icon = QIcon()
        icon.addFile(u":/Art/Icons/PathOfBuilding.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.action_New = QAction(MainWindow)
        self.action_New.setObjectName(u"action_New")
        icon1 = QIcon()
        icon1.addFile(u":/Art/Icons/add-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_New.setIcon(icon1)
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName(u"action_Save")
        icon2 = QIcon()
        icon2.addFile(u":/Art/Icons/downloads-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Save.setIcon(icon2)
        self.action_Exit = QAction(MainWindow)
        self.action_Exit.setObjectName(u"action_Exit")
        icon3 = QIcon()
        icon3.addFile(u":/Art/Icons/door-open-out.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Exit.setIcon(icon3)
        self.action_Open = QAction(MainWindow)
        self.action_Open.setObjectName(u"action_Open")
        icon4 = QIcon()
        icon4.addFile(u":/Art/Icons/opened-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Open.setIcon(icon4)
        self.action_ManageTrees = QAction(MainWindow)
        self.action_ManageTrees.setObjectName(u"action_ManageTrees")
        icon5 = QIcon()
        icon5.addFile(u":/Art/Icons/tree--pencil.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_ManageTrees.setIcon(icon5)
        self.action_Settings = QAction(MainWindow)
        self.action_Settings.setObjectName(u"action_Settings")
        icon6 = QIcon()
        icon6.addFile(u":/Art/Icons/construction.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Settings.setIcon(icon6)
        self.action_Import = QAction(MainWindow)
        self.action_Import.setObjectName(u"action_Import")
        icon7 = QIcon()
        icon7.addFile(u":/Art/Icons/paper-plane-return.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Import.setIcon(icon7)
        self.action_Export = QAction(MainWindow)
        self.action_Export.setObjectName(u"action_Export")
        icon8 = QIcon()
        icon8.addFile(u":/Art/Icons/paper-plane.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Export.setIcon(icon8)
        self.action_SaveAs = QAction(MainWindow)
        self.action_SaveAs.setObjectName(u"action_SaveAs")
        self.action_SaveAs.setIcon(icon2)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.hlayout_MainWindow = QHBoxLayout(self.centralwidget)
        self.hlayout_MainWindow.setObjectName(u"hlayout_MainWindow")
        self.hlayout_MainWindow.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setMinimumSize(QSize(0, 0))
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1419, 782))
        self.scrollAreaWidgetContents.setMinimumSize(QSize(1280, 700))
        self.horizontalLayout_5 = QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(3, 0, 0, 0)
        self.splitter_MainWindow = QSplitter(self.scrollAreaWidgetContents)
        self.splitter_MainWindow.setObjectName(u"splitter_MainWindow")
        self.splitter_MainWindow.setAutoFillBackground(False)
        self.splitter_MainWindow.setStyleSheet(u"")
        self.splitter_MainWindow.setLineWidth(8)
        self.splitter_MainWindow.setMidLineWidth(10)
        self.splitter_MainWindow.setOrientation(Qt.Horizontal)
        self.frame_Left = QFrame(self.splitter_MainWindow)
        self.frame_Left.setObjectName(u"frame_Left")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Left.sizePolicy().hasHeightForWidth())
        self.frame_Left.setSizePolicy(sizePolicy)
        self.frame_Left.setMinimumSize(QSize(240, 600))
        self.frame_Left.setMaximumSize(QSize(300, 16777215))
        self.frame_Left.setSizeIncrement(QSize(10, 0))
        self.frame_Left.setBaseSize(QSize(200, 0))
        self.frame_Left.setFrameShadow(QFrame.Raised)
        self.glayout_LeftFrame = QGridLayout(self.frame_Left)
        self.glayout_LeftFrame.setObjectName(u"glayout_LeftFrame")
        self.glayout_LeftFrame.setContentsMargins(2, 2, 2, 2)
        self.combo_MainSkill = QComboBox(self.frame_Left)
        self.combo_MainSkill.setObjectName(u"combo_MainSkill")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.combo_MainSkill.sizePolicy().hasHeightForWidth())
        self.combo_MainSkill.setSizePolicy(sizePolicy1)
        self.combo_MainSkill.setMinimumSize(QSize(180, 0))
        self.combo_MainSkill.setMaximumSize(QSize(280, 16777215))
        self.combo_MainSkill.setDuplicatesEnabled(True)

        self.glayout_LeftFrame.addWidget(self.combo_MainSkill, 1, 0, 1, 1)

        self.combo_MainSkillActive = QComboBox(self.frame_Left)
        self.combo_MainSkillActive.setObjectName(u"combo_MainSkillActive")
        sizePolicy1.setHeightForWidth(self.combo_MainSkillActive.sizePolicy().hasHeightForWidth())
        self.combo_MainSkillActive.setSizePolicy(sizePolicy1)
        self.combo_MainSkillActive.setMinimumSize(QSize(180, 0))
        self.combo_MainSkillActive.setMaximumSize(QSize(280, 16777215))

        self.glayout_LeftFrame.addWidget(self.combo_MainSkillActive, 2, 0, 1, 1)

        self.textedit_Statistics = QTextEdit(self.frame_Left)
        self.textedit_Statistics.setObjectName(u"textedit_Statistics")
        self.textedit_Statistics.setEnabled(True)
        self.textedit_Statistics.setMinimumSize(QSize(330, 0))
        font = QFont()
        font.setFamilies([u"Noto Mono"])
        self.textedit_Statistics.setFont(font)
        self.textedit_Statistics.setFocusPolicy(Qt.NoFocus)
        self.textedit_Statistics.setFrameShape(QFrame.NoFrame)
        self.textedit_Statistics.setLineWrapMode(QTextEdit.NoWrap)
        self.textedit_Statistics.setHtml(u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Noto Mono'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")

        self.glayout_LeftFrame.addWidget(self.textedit_Statistics, 3, 0, 1, 1)

        self.label_MainSkill = QLabel(self.frame_Left)
        self.label_MainSkill.setObjectName(u"label_MainSkill")
        self.label_MainSkill.setMinimumSize(QSize(0, 0))

        self.glayout_LeftFrame.addWidget(self.label_MainSkill, 0, 0, 1, 1)

        self.splitter_MainWindow.addWidget(self.frame_Left)
        self.tab_main = QTabWidget(self.splitter_MainWindow)
        self.tab_main.setObjectName(u"tab_main")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(2)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.tab_main.sizePolicy().hasHeightForWidth())
        self.tab_main.setSizePolicy(sizePolicy2)
        self.tab_main.setMinimumSize(QSize(910, 655))
        self.tab_main.setFocusPolicy(Qt.NoFocus)
        self.tab_main.setStyleSheet(u"")
        self.tab_Tree = QWidget()
        self.tab_Tree.setObjectName(u"tab_Tree")
        self.tab_Tree.setMinimumSize(QSize(0, 0))
        self.horizontalLayout_7 = QHBoxLayout(self.tab_Tree)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.vlayout_tabTree = QVBoxLayout()
        self.vlayout_tabTree.setSpacing(0)
        self.vlayout_tabTree.setObjectName(u"vlayout_tabTree")
        self.graphicsView_PlaceHolder = QGraphicsView(self.tab_Tree)
        self.graphicsView_PlaceHolder.setObjectName(u"graphicsView_PlaceHolder")

        self.vlayout_tabTree.addWidget(self.graphicsView_PlaceHolder)

        self.frame_TreeTools = QFrame(self.tab_Tree)
        self.frame_TreeTools.setObjectName(u"frame_TreeTools")
        self.frame_TreeTools.setMinimumSize(QSize(0, 30))
        self.frame_TreeTools.setMaximumSize(QSize(16777215, 30))
        self.frame_TreeTools.setStyleSheet(u"")
        self.frame_TreeTools.setFrameShape(QFrame.StyledPanel)

        self.vlayout_tabTree.addWidget(self.frame_TreeTools)


        self.horizontalLayout_7.addLayout(self.vlayout_tabTree)

        self.tab_main.addTab(self.tab_Tree, "")
#if QT_CONFIG(whatsthis)
        self.tab_main.setTabWhatsThis(self.tab_main.indexOf(self.tab_Tree), u"TREE")
#endif // QT_CONFIG(whatsthis)
        self.tab_Skills = QWidget()
        self.tab_Skills.setObjectName(u"tab_Skills")
        self.hLayout_Skills = QHBoxLayout(self.tab_Skills)
        self.hLayout_Skills.setSpacing(0)
        self.hLayout_Skills.setObjectName(u"hLayout_Skills")
        self.hLayout_Skills.setContentsMargins(0, 0, 0, 0)
        self.frame_SkillsLeft = QFrame(self.tab_Skills)
        self.frame_SkillsLeft.setObjectName(u"frame_SkillsLeft")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.frame_SkillsLeft.sizePolicy().hasHeightForWidth())
        self.frame_SkillsLeft.setSizePolicy(sizePolicy3)
        self.frame_SkillsLeft.setMinimumSize(QSize(400, 655))
        self.frame_SkillsLeft.setFrameShadow(QFrame.Raised)
        self.label_Usage_Hints = QLabel(self.frame_SkillsLeft)
        self.label_Usage_Hints.setObjectName(u"label_Usage_Hints")
        self.label_Usage_Hints.setGeometry(QRect(10, 385, 375, 91))
        font1 = QFont()
        font1.setStrikeOut(True)
        self.label_Usage_Hints.setFont(font1)
        self.label_Usage_Hints.setScaledContents(True)
        self.list_SocketGroups = ListBox(self.frame_SkillsLeft)
        self.list_SocketGroups.setObjectName(u"list_SocketGroups")
        self.list_SocketGroups.setGeometry(QRect(10, 70, 385, 311))
        self.list_SocketGroups.setFocusPolicy(Qt.StrongFocus)
        self.list_SocketGroups.setStyleSheet(u"")
        self.list_SocketGroups.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.list_SocketGroups.setDragEnabled(True)
        self.list_SocketGroups.setDragDropMode(QAbstractItemView.InternalMove)
        self.list_SocketGroups.setDefaultDropAction(Qt.MoveAction)
        self.list_SocketGroups.setAlternatingRowColors(False)
        self.list_SocketGroups.setSelectionMode(QAbstractItemView.SingleSelection)
        self.list_SocketGroups.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.group_SkillTabLeft = QGroupBox(self.frame_SkillsLeft)
        self.group_SkillTabLeft.setObjectName(u"group_SkillTabLeft")
        self.group_SkillTabLeft.setGeometry(QRect(0, 480, 400, 170))
        self.group_SkillTabLeft.setMinimumSize(QSize(375, 170))
        self.label_DefaultGemQuality = QLabel(self.group_SkillTabLeft)
        self.label_DefaultGemQuality.setObjectName(u"label_DefaultGemQuality")
        self.label_DefaultGemQuality.setGeometry(QRect(10, 105, 170, 22))
        self.label_DefaultGemQuality.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.combo_SortByDPS = QComboBox(self.group_SkillTabLeft)
        self.combo_SortByDPS.setObjectName(u"combo_SortByDPS")
        self.combo_SortByDPS.setGeometry(QRect(210, 15, 180, 22))
        self.spin_DefaultGemQuality = QSpinBox(self.group_SkillTabLeft)
        self.spin_DefaultGemQuality.setObjectName(u"spin_DefaultGemQuality")
        self.spin_DefaultGemQuality.setGeometry(QRect(190, 105, 50, 24))
        self.spin_DefaultGemQuality.setMaximum(40)
        self.check_SortByDPS = QCheckBox(self.group_SkillTabLeft)
        self.check_SortByDPS.setObjectName(u"check_SortByDPS")
        self.check_SortByDPS.setGeometry(QRect(10, 15, 196, 20))
        self.check_SortByDPS.setLayoutDirection(Qt.RightToLeft)
        self.check_ShowGemQualityVariants = QCheckBox(self.group_SkillTabLeft)
        self.check_ShowGemQualityVariants.setObjectName(u"check_ShowGemQualityVariants")
        self.check_ShowGemQualityVariants.setGeometry(QRect(10, 135, 196, 20))
        self.check_ShowGemQualityVariants.setLayoutDirection(Qt.RightToLeft)
        self.label_ShowSupportGems = QLabel(self.group_SkillTabLeft)
        self.label_ShowSupportGems.setObjectName(u"label_ShowSupportGems")
        self.label_ShowSupportGems.setGeometry(QRect(10, 75, 170, 22))
        self.label_ShowSupportGems.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.combo_ShowSupportGems = QComboBox(self.group_SkillTabLeft)
        self.combo_ShowSupportGems.setObjectName(u"combo_ShowSupportGems")
        self.combo_ShowSupportGems.setGeometry(QRect(190, 75, 200, 22))
        self.combo_DefaultGemLevel = QComboBox(self.group_SkillTabLeft)
        self.combo_DefaultGemLevel.setObjectName(u"combo_DefaultGemLevel")
        self.combo_DefaultGemLevel.setGeometry(QRect(190, 45, 200, 22))
        self.label_DefaultGemLevel = QLabel(self.group_SkillTabLeft)
        self.label_DefaultGemLevel.setObjectName(u"label_DefaultGemLevel")
        self.label_DefaultGemLevel.setGeometry(QRect(10, 45, 170, 22))
        self.label_DefaultGemLevel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.combo_SkillSet = QComboBox(self.frame_SkillsLeft)
        self.combo_SkillSet.setObjectName(u"combo_SkillSet")
        self.combo_SkillSet.setGeometry(QRect(110, 10, 190, 22))
        self.combo_SkillSet.setMaxVisibleItems(15)
        self.combo_SkillSet.setDuplicatesEnabled(True)
        self.btn_NewSocketGroup = QPushButton(self.frame_SkillsLeft)
        self.btn_NewSocketGroup.setObjectName(u"btn_NewSocketGroup")
        self.btn_NewSocketGroup.setGeometry(QRect(110, 40, 80, 22))
        self.label_SocketGroups = QLabel(self.frame_SkillsLeft)
        self.label_SocketGroups.setObjectName(u"label_SocketGroups")
        self.label_SocketGroups.setGeometry(QRect(10, 40, 90, 22))
        self.label_SocketGroups.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_DeleteAllSocketGroups = QPushButton(self.frame_SkillsLeft)
        self.btn_DeleteAllSocketGroups.setObjectName(u"btn_DeleteAllSocketGroups")
        self.btn_DeleteAllSocketGroups.setGeometry(QRect(315, 40, 80, 22))
        self.label_SkillSet = QLabel(self.frame_SkillsLeft)
        self.label_SkillSet.setObjectName(u"label_SkillSet")
        self.label_SkillSet.setGeometry(QRect(10, 10, 90, 22))
        self.label_SkillSet.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.btn_SkillsManage = QPushButton(self.frame_SkillsLeft)
        self.btn_SkillsManage.setObjectName(u"btn_SkillsManage")
        self.btn_SkillsManage.setEnabled(True)
        self.btn_SkillsManage.setGeometry(QRect(315, 10, 80, 22))
        self.btn_DeleteSocketGroup = QPushButton(self.frame_SkillsLeft)
        self.btn_DeleteSocketGroup.setObjectName(u"btn_DeleteSocketGroup")
        self.btn_DeleteSocketGroup.setGeometry(QRect(220, 40, 80, 22))

        self.hLayout_Skills.addWidget(self.frame_SkillsLeft)

        self.frame_SkillsRight = QFrame(self.tab_Skills)
        self.frame_SkillsRight.setObjectName(u"frame_SkillsRight")
        self.frame_SkillsRight.setFrameShadow(QFrame.Raised)
        self.frame_SkillsRight.setMidLineWidth(1)
        self.vlayout_SkillsRight = QVBoxLayout(self.frame_SkillsRight)
        self.vlayout_SkillsRight.setSpacing(0)
        self.vlayout_SkillsRight.setObjectName(u"vlayout_SkillsRight")
        self.vlayout_SkillsRight.setContentsMargins(0, 0, 0, 0)
        self.frame_SkillsRightTop = QFrame(self.frame_SkillsRight)
        self.frame_SkillsRightTop.setObjectName(u"frame_SkillsRightTop")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.frame_SkillsRightTop.sizePolicy().hasHeightForWidth())
        self.frame_SkillsRightTop.setSizePolicy(sizePolicy4)
        self.frame_SkillsRightTop.setMinimumSize(QSize(610, 100))
        self.frame_SkillsRightTop.setFrameShape(QFrame.NoFrame)
        self.frame_SkillsRightTop.setFrameShadow(QFrame.Raised)
        self.label_GemName = QLabel(self.frame_SkillsRightTop)
        self.label_GemName.setObjectName(u"label_GemName")
        self.label_GemName.setGeometry(QRect(27, 70, 70, 22))
        self.combo_SocketedIn = QComboBox(self.frame_SkillsRightTop)
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.addItem("")
        self.combo_SocketedIn.setObjectName(u"combo_SocketedIn")
        self.combo_SocketedIn.setGeometry(QRect(80, 40, 171, 22))
        self.combo_SocketedIn.setDuplicatesEnabled(False)
        self.label_Variant = QLabel(self.frame_SkillsRightTop)
        self.label_Variant.setObjectName(u"label_Variant")
        self.label_Variant.setGeometry(QRect(420, 70, 40, 22))
        self.label_SkillLabel = QLabel(self.frame_SkillsRightTop)
        self.label_SkillLabel.setObjectName(u"label_SkillLabel")
        self.label_SkillLabel.setGeometry(QRect(10, 10, 65, 22))
        self.label_SkillLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_Enabled = QLabel(self.frame_SkillsRightTop)
        self.label_Enabled.setObjectName(u"label_Enabled")
        self.label_Enabled.setGeometry(QRect(510, 70, 50, 22))
        self.label_Quality = QLabel(self.frame_SkillsRightTop)
        self.label_Quality.setObjectName(u"label_Quality")
        self.label_Quality.setGeometry(QRect(360, 70, 45, 22))
        self.lineedit_SkillLabel = QLineEdit(self.frame_SkillsRightTop)
        self.lineedit_SkillLabel.setObjectName(u"lineedit_SkillLabel")
        self.lineedit_SkillLabel.setGeometry(QRect(80, 10, 400, 24))
        self.lineedit_SkillLabel.setMinimumSize(QSize(0, 24))
        self.label_Count = QLabel(self.frame_SkillsRightTop)
        self.label_Count.setObjectName(u"label_Count")
        self.label_Count.setGeometry(QRect(570, 70, 40, 22))
        self.label_SocketedIn = QLabel(self.frame_SkillsRightTop)
        self.label_SocketedIn.setObjectName(u"label_SocketedIn")
        self.label_SocketedIn.setGeometry(QRect(0, 40, 75, 22))
        self.label_SocketedIn.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_Level = QLabel(self.frame_SkillsRightTop)
        self.label_Level.setObjectName(u"label_Level")
        self.label_Level.setGeometry(QRect(300, 70, 40, 22))
        self.check_SocketGroupEnabled = QCheckBox(self.frame_SkillsRightTop)
        self.check_SocketGroupEnabled.setObjectName(u"check_SocketGroupEnabled")
        self.check_SocketGroupEnabled.setGeometry(QRect(260, 40, 75, 20))
        self.check_SocketGroupEnabled.setChecked(False)
        self.check_SocketGroup_FullDPS = QCheckBox(self.frame_SkillsRightTop)
        self.check_SocketGroup_FullDPS.setObjectName(u"check_SocketGroup_FullDPS")
        self.check_SocketGroup_FullDPS.setGeometry(QRect(350, 40, 130, 20))
        self.check_SocketGroup_FullDPS.setChecked(False)

        self.vlayout_SkillsRight.addWidget(self.frame_SkillsRightTop)

        self.list_Skills = QListWidget(self.frame_SkillsRight)
        self.list_Skills.setObjectName(u"list_Skills")
        self.list_Skills.setFrameShape(QFrame.NoFrame)
        self.list_Skills.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.list_Skills.setDragEnabled(True)
        self.list_Skills.setDragDropMode(QAbstractItemView.InternalMove)
        self.list_Skills.setDefaultDropAction(Qt.MoveAction)
        self.list_Skills.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.list_Skills.setMovement(QListView.Free)
        self.list_Skills.setLayoutMode(QListView.SinglePass)
        self.list_Skills.setSpacing(0)
        self.list_Skills.setUniformItemSizes(True)
        self.list_Skills.setBatchSize(3)
        self.list_Skills.setSelectionRectVisible(True)

        self.vlayout_SkillsRight.addWidget(self.list_Skills)


        self.hLayout_Skills.addWidget(self.frame_SkillsRight)

        self.tab_main.addTab(self.tab_Skills, "")
#if QT_CONFIG(whatsthis)
        self.tab_main.setTabWhatsThis(self.tab_main.indexOf(self.tab_Skills), u"SKILLS")
#endif // QT_CONFIG(whatsthis)
        self.tab_Items = QWidget()
        self.tab_Items.setObjectName(u"tab_Items")
        self.horizontalLayout = QHBoxLayout(self.tab_Items)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_Items = QScrollArea(self.tab_Items)
        self.scrollArea_Items.setObjectName(u"scrollArea_Items")
        self.scrollArea_Items.setWidgetResizable(True)
        self.scrollAreaWidgetContents_Items = QWidget()
        self.scrollAreaWidgetContents_Items.setObjectName(u"scrollAreaWidgetContents_Items")
        self.scrollAreaWidgetContents_Items.setGeometry(QRect(0, 0, 1146, 792))
        self.scrollAreaWidgetContents_Items.setMaximumSize(QSize(16777215, 900))
        self.horizontalLayout_2 = QHBoxLayout(self.scrollAreaWidgetContents_Items)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_Items = QFrame(self.scrollAreaWidgetContents_Items)
        self.frame_Items.setObjectName(u"frame_Items")
        self.frame_Items.setFrameShape(QFrame.StyledPanel)
        self.frame_Items.setFrameShadow(QFrame.Raised)
        self.vlayout_Items2 = QVBoxLayout(self.frame_Items)
        self.vlayout_Items2.setObjectName(u"vlayout_Items2")
        self.vlayout_Items2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(-1, 3, 0, -1)
        self.label_ItemSet = QLabel(self.frame_Items)
        self.label_ItemSet.setObjectName(u"label_ItemSet")
        self.label_ItemSet.setMinimumSize(QSize(65, 24))
        self.label_ItemSet.setMaximumSize(QSize(65, 24))
        self.label_ItemSet.setFrameShape(QFrame.NoFrame)
        self.label_ItemSet.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_4.addWidget(self.label_ItemSet)

        self.combo_ItemSet = QComboBox(self.frame_Items)
        self.combo_ItemSet.setObjectName(u"combo_ItemSet")
        self.combo_ItemSet.setMinimumSize(QSize(0, 24))
        self.combo_ItemSet.setMaximumSize(QSize(16777215, 24))
        self.combo_ItemSet.setCurrentText(u"")
        self.combo_ItemSet.setMaxVisibleItems(15)
        self.combo_ItemSet.setDuplicatesEnabled(True)

        self.horizontalLayout_4.addWidget(self.combo_ItemSet)

        self.btn_ManageItemSet = QPushButton(self.frame_Items)
        self.btn_ManageItemSet.setObjectName(u"btn_ManageItemSet")
        self.btn_ManageItemSet.setMinimumSize(QSize(85, 24))
        self.btn_ManageItemSet.setMaximumSize(QSize(85, 24))

        self.horizontalLayout_4.addWidget(self.btn_ManageItemSet)


        self.vlayout_Items2.addLayout(self.horizontalLayout_4)

        self.frame_EquippedItems = QFrame(self.frame_Items)
        self.frame_EquippedItems.setObjectName(u"frame_EquippedItems")
        self.frame_EquippedItems.setMinimumSize(QSize(0, 450))
        self.frame_EquippedItems.setMaximumSize(QSize(16777215, 1000))
        self.layout_EquippedItems = QVBoxLayout(self.frame_EquippedItems)
        self.layout_EquippedItems.setSpacing(2)
        self.layout_EquippedItems.setObjectName(u"layout_EquippedItems")
        self.layout_EquippedItems.setContentsMargins(0, 0, 0, 0)
        self.hlayout_EquippedItems = QHBoxLayout()
        self.hlayout_EquippedItems.setSpacing(6)
        self.hlayout_EquippedItems.setObjectName(u"hlayout_EquippedItems")
        self.label_EquippedItems = QLabel(self.frame_EquippedItems)
        self.label_EquippedItems.setObjectName(u"label_EquippedItems")
        self.label_EquippedItems.setMinimumSize(QSize(0, 24))
        self.label_EquippedItems.setMaximumSize(QSize(16777215, 24))

        self.hlayout_EquippedItems.addWidget(self.label_EquippedItems)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.hlayout_EquippedItems.addItem(self.horizontalSpacer)

        self.btn_WeaponSwap = QPushButton(self.frame_EquippedItems)
        self.btn_WeaponSwap.setObjectName(u"btn_WeaponSwap")
        self.btn_WeaponSwap.setMinimumSize(QSize(135, 24))
        self.btn_WeaponSwap.setMaximumSize(QSize(135, 24))
        self.btn_WeaponSwap.setCheckable(True)

        self.hlayout_EquippedItems.addWidget(self.btn_WeaponSwap)


        self.layout_EquippedItems.addLayout(self.hlayout_EquippedItems)


        self.vlayout_Items2.addWidget(self.frame_EquippedItems)

        self.frame_SocketedJewels = QFrame(self.frame_Items)
        self.frame_SocketedJewels.setObjectName(u"frame_SocketedJewels")
        self.frame_SocketedJewels.setMinimumSize(QSize(0, 100))
        self.verticalLayout_5 = QVBoxLayout(self.frame_SocketedJewels)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_SocketedJewels = QLabel(self.frame_SocketedJewels)
        self.label_SocketedJewels.setObjectName(u"label_SocketedJewels")
        self.label_SocketedJewels.setMinimumSize(QSize(0, 24))
        self.label_SocketedJewels.setMaximumSize(QSize(16777215, 24))

        self.verticalLayout_5.addWidget(self.label_SocketedJewels)

        self.horizontalLayout_14 = QHBoxLayout()
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.label_ItemsPassiveTree = QLabel(self.frame_SocketedJewels)
        self.label_ItemsPassiveTree.setObjectName(u"label_ItemsPassiveTree")
        self.label_ItemsPassiveTree.setMinimumSize(QSize(0, 24))
        self.label_ItemsPassiveTree.setMaximumSize(QSize(85, 24))
        self.label_ItemsPassiveTree.setLayoutDirection(Qt.LeftToRight)
        self.label_ItemsPassiveTree.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_14.addWidget(self.label_ItemsPassiveTree)

        self.combo_ItemsManageTree = QComboBox(self.frame_SocketedJewels)
        self.combo_ItemsManageTree.setObjectName(u"combo_ItemsManageTree")
        self.combo_ItemsManageTree.setMinimumSize(QSize(0, 24))
        self.combo_ItemsManageTree.setMaximumSize(QSize(16777215, 24))
        self.combo_ItemsManageTree.setSizeAdjustPolicy(QComboBox.AdjustToContents)

        self.horizontalLayout_14.addWidget(self.combo_ItemsManageTree)

        self.btn_ItemsManageTree = QPushButton(self.frame_SocketedJewels)
        self.btn_ItemsManageTree.setObjectName(u"btn_ItemsManageTree")
        self.btn_ItemsManageTree.setMinimumSize(QSize(85, 24))
        self.btn_ItemsManageTree.setMaximumSize(QSize(75, 24))
        self.btn_ItemsManageTree.setCheckable(True)

        self.horizontalLayout_14.addWidget(self.btn_ItemsManageTree)


        self.verticalLayout_5.addLayout(self.horizontalLayout_14)

        self.scrollArea_SocketedJewels = QScrollArea(self.frame_SocketedJewels)
        self.scrollArea_SocketedJewels.setObjectName(u"scrollArea_SocketedJewels")
        self.scrollArea_SocketedJewels.setWidgetResizable(True)
        self.scrollAreaWidgetContents_SocketedJewels = QWidget()
        self.scrollAreaWidgetContents_SocketedJewels.setObjectName(u"scrollAreaWidgetContents_SocketedJewels")
        self.scrollAreaWidgetContents_SocketedJewels.setGeometry(QRect(0, 0, 362, 150))
        self.layout_SocketedJewels = QVBoxLayout(self.scrollAreaWidgetContents_SocketedJewels)
        self.layout_SocketedJewels.setSpacing(2)
        self.layout_SocketedJewels.setObjectName(u"layout_SocketedJewels")
        self.layout_SocketedJewels.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_SocketedJewels.setWidget(self.scrollAreaWidgetContents_SocketedJewels)

        self.verticalLayout_5.addWidget(self.scrollArea_SocketedJewels)


        self.vlayout_Items2.addWidget(self.frame_SocketedJewels)

        self.verticalSpacer = QSpacerItem(20, 13, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.vlayout_Items2.addItem(self.verticalSpacer)

        self.vlayout_Items2.setStretch(0, 1)
        self.vlayout_Items2.setStretch(1, 2)
        self.vlayout_Items2.setStretch(2, 2)

        self.horizontalLayout_2.addWidget(self.frame_Items)

        self.frame_ItemsList = QFrame(self.scrollAreaWidgetContents_Items)
        self.frame_ItemsList.setObjectName(u"frame_ItemsList")
        self.frame_ItemsList.setFrameShape(QFrame.StyledPanel)
        self.frame_ItemsList.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_ItemsList)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15 = QHBoxLayout()
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.label_AllItems = QLabel(self.frame_ItemsList)
        self.label_AllItems.setObjectName(u"label_AllItems")

        self.horizontalLayout_15.addWidget(self.label_AllItems)

        self.btn_SortItems = QPushButton(self.frame_ItemsList)
        self.btn_SortItems.setObjectName(u"btn_SortItems")

        self.horizontalLayout_15.addWidget(self.btn_SortItems)

        self.btn_DeleteAllItems = QPushButton(self.frame_ItemsList)
        self.btn_DeleteAllItems.setObjectName(u"btn_DeleteAllItems")

        self.horizontalLayout_15.addWidget(self.btn_DeleteAllItems)

        self.btn_DeleteItem = QPushButton(self.frame_ItemsList)
        self.btn_DeleteItem.setObjectName(u"btn_DeleteItem")
        self.btn_DeleteItem.setEnabled(False)

        self.horizontalLayout_15.addWidget(self.btn_DeleteItem)

        self.btn_DeleteUnusedItems = QPushButton(self.frame_ItemsList)
        self.btn_DeleteUnusedItems.setObjectName(u"btn_DeleteUnusedItems")

        self.horizontalLayout_15.addWidget(self.btn_DeleteUnusedItems)


        self.verticalLayout_4.addLayout(self.horizontalLayout_15)

        self.horizontalLayout_10 = QHBoxLayout()
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.label_ItemsSearch = QLabel(self.frame_ItemsList)
        self.label_ItemsSearch.setObjectName(u"label_ItemsSearch")
        self.label_ItemsSearch.setLayoutDirection(Qt.LeftToRight)

        self.horizontalLayout_10.addWidget(self.label_ItemsSearch)

        self.lineedit_ItemsSearch = QLineEdit(self.frame_ItemsList)
        self.lineedit_ItemsSearch.setObjectName(u"lineedit_ItemsSearch")
        self.lineedit_ItemsSearch.setMinimumSize(QSize(0, 24))

        self.horizontalLayout_10.addWidget(self.lineedit_ItemsSearch)


        self.verticalLayout_4.addLayout(self.horizontalLayout_10)

        self.list_Items = ListBox(self.frame_ItemsList)
        self.list_Items.setObjectName(u"list_Items")
        self.list_Items.setMinimumSize(QSize(400, 600))
        self.list_Items.setMaximumSize(QSize(600, 890))
        self.list_Items.setAcceptDrops(True)
        self.list_Items.setEditTriggers(QAbstractItemView.DoubleClicked)
        self.list_Items.setDragEnabled(True)
        self.list_Items.setDragDropMode(QAbstractItemView.DropOnly)
        self.list_Items.setDefaultDropAction(Qt.MoveAction)
        self.list_Items.setAlternatingRowColors(False)

        self.verticalLayout_4.addWidget(self.list_Items)

        self.verticalSpacer_3 = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_4.addItem(self.verticalSpacer_3)


        self.horizontalLayout_2.addWidget(self.frame_ItemsList)

        self.frame_TemplateItems = QFrame(self.scrollAreaWidgetContents_Items)
        self.frame_TemplateItems.setObjectName(u"frame_TemplateItems")
        self.frame_TemplateItems.setFrameShape(QFrame.StyledPanel)
        self.frame_TemplateItems.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_TemplateItems)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.label_6 = QLabel(self.frame_TemplateItems)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setWordWrap(True)

        self.verticalLayout_3.addWidget(self.label_6)

        self.horizontalLayout_9 = QHBoxLayout()
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.label_ItemsImportFrom = QLabel(self.frame_TemplateItems)
        self.label_ItemsImportFrom.setObjectName(u"label_ItemsImportFrom")
        self.label_ItemsImportFrom.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout_9.addWidget(self.label_ItemsImportFrom)

        self.combo_ItemsImportFrom = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportFrom.addItem("")
        self.combo_ItemsImportFrom.addItem("")
        self.combo_ItemsImportFrom.setObjectName(u"combo_ItemsImportFrom")
        self.combo_ItemsImportFrom.setMaxVisibleItems(15)

        self.horizontalLayout_9.addWidget(self.combo_ItemsImportFrom)


        self.verticalLayout_3.addLayout(self.horizontalLayout_9)

        self.horizontalLayout_11 = QHBoxLayout()
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.combo_ItemsImportSlot = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.addItem("")
        self.combo_ItemsImportSlot.setObjectName(u"combo_ItemsImportSlot")
        self.combo_ItemsImportSlot.setMinimumSize(QSize(150, 0))
        self.combo_ItemsImportSlot.setMaxVisibleItems(15)

        self.horizontalLayout_11.addWidget(self.combo_ItemsImportSlot)

        self.combo_ItemsImportType = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportType.addItem("")
        self.combo_ItemsImportType.setObjectName(u"combo_ItemsImportType")
        self.combo_ItemsImportType.setMinimumSize(QSize(150, 0))
        self.combo_ItemsImportType.setMaxVisibleItems(15)

        self.horizontalLayout_11.addWidget(self.combo_ItemsImportType)


        self.verticalLayout_3.addLayout(self.horizontalLayout_11)

        self.horizontalLayout_12 = QHBoxLayout()
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.combo_ItemsImportSort = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportSort.addItem("")
        self.combo_ItemsImportSort.setObjectName(u"combo_ItemsImportSort")
        self.combo_ItemsImportSort.setEnabled(True)
        self.combo_ItemsImportSort.setMinimumSize(QSize(150, 0))
        self.combo_ItemsImportSort.setMaxVisibleItems(15)

        self.horizontalLayout_12.addWidget(self.combo_ItemsImportSort)

        self.combo_ItemsImportLeague = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportLeague.addItem("")
        self.combo_ItemsImportLeague.addItem("")
        self.combo_ItemsImportLeague.setObjectName(u"combo_ItemsImportLeague")
        self.combo_ItemsImportLeague.setMinimumSize(QSize(150, 0))
        self.combo_ItemsImportLeague.setMaxVisibleItems(15)

        self.horizontalLayout_12.addWidget(self.combo_ItemsImportLeague)


        self.verticalLayout_3.addLayout(self.horizontalLayout_12)

        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.combo_ItemsImportRequirements = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportRequirements.addItem("")
        self.combo_ItemsImportRequirements.addItem("")
        self.combo_ItemsImportRequirements.addItem("")
        self.combo_ItemsImportRequirements.addItem("")
        self.combo_ItemsImportRequirements.setObjectName(u"combo_ItemsImportRequirements")
        self.combo_ItemsImportRequirements.setEnabled(False)
        self.combo_ItemsImportRequirements.setMinimumSize(QSize(150, 0))
        self.combo_ItemsImportRequirements.setMaxVisibleItems(15)

        self.horizontalLayout_13.addWidget(self.combo_ItemsImportRequirements)

        self.combo_ItemsImportSource = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportSource.addItem("")
        self.combo_ItemsImportSource.addItem("")
        self.combo_ItemsImportSource.addItem("")
        self.combo_ItemsImportSource.addItem("")
        self.combo_ItemsImportSource.addItem("")
        self.combo_ItemsImportSource.addItem("")
        self.combo_ItemsImportSource.addItem("")
        self.combo_ItemsImportSource.setObjectName(u"combo_ItemsImportSource")
        self.combo_ItemsImportSource.setEnabled(True)
        self.combo_ItemsImportSource.setMinimumSize(QSize(150, 0))
        self.combo_ItemsImportSource.setMaxVisibleItems(15)

        self.horizontalLayout_13.addWidget(self.combo_ItemsImportSource)


        self.verticalLayout_3.addLayout(self.horizontalLayout_13)

        self.horizontalLayout_8 = QHBoxLayout()
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.label_ImportItemsSearch = QLabel(self.frame_TemplateItems)
        self.label_ImportItemsSearch.setObjectName(u"label_ImportItemsSearch")
        self.label_ImportItemsSearch.setLayoutDirection(Qt.LeftToRight)

        self.horizontalLayout_8.addWidget(self.label_ImportItemsSearch)

        self.lineedit_ItemsImportSearch = QLineEdit(self.frame_TemplateItems)
        self.lineedit_ItemsImportSearch.setObjectName(u"lineedit_ItemsImportSearch")
        self.lineedit_ItemsImportSearch.setMinimumSize(QSize(0, 24))

        self.horizontalLayout_8.addWidget(self.lineedit_ItemsImportSearch)

        self.combo_ItemsImportSearchSource = QComboBox(self.frame_TemplateItems)
        self.combo_ItemsImportSearchSource.addItem("")
        self.combo_ItemsImportSearchSource.addItem("")
        self.combo_ItemsImportSearchSource.addItem("")
        self.combo_ItemsImportSearchSource.setObjectName(u"combo_ItemsImportSearchSource")
        self.combo_ItemsImportSearchSource.setMaxVisibleItems(15)

        self.horizontalLayout_8.addWidget(self.combo_ItemsImportSearchSource)


        self.verticalLayout_3.addLayout(self.horizontalLayout_8)

        self.list_ImportItems = ListBox(self.frame_TemplateItems)
        self.list_ImportItems.setObjectName(u"list_ImportItems")
        self.list_ImportItems.setMinimumSize(QSize(350, 450))
        self.list_ImportItems.setMaximumSize(QSize(16777215, 700))
        self.list_ImportItems.setSortingEnabled(False)

        self.verticalLayout_3.addWidget(self.list_ImportItems)


        self.horizontalLayout_2.addWidget(self.frame_TemplateItems)

        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 2)
        self.scrollArea_Items.setWidget(self.scrollAreaWidgetContents_Items)

        self.horizontalLayout.addWidget(self.scrollArea_Items)

        self.tab_main.addTab(self.tab_Items, "")
        self.tab_Notes = QWidget()
        self.tab_Notes.setObjectName(u"tab_Notes")
        self.tab_Notes.setMinimumSize(QSize(910, 655))
        self.vlayout_Notes = QVBoxLayout(self.tab_Notes)
        self.vlayout_Notes.setObjectName(u"vlayout_Notes")
        self.vlayout_Notes.setContentsMargins(0, 3, 0, 0)
        self.hlayout_Notes = QHBoxLayout()
        self.hlayout_Notes.setSpacing(16)
        self.hlayout_Notes.setObjectName(u"hlayout_Notes")
        self.combo_Notes_Font = QFontComboBox(self.tab_Notes)
        self.combo_Notes_Font.setObjectName(u"combo_Notes_Font")
        self.combo_Notes_Font.setMinimumSize(QSize(200, 0))
        self.combo_Notes_Font.setEditable(False)
        self.combo_Notes_Font.setMaxVisibleItems(15)

        self.hlayout_Notes.addWidget(self.combo_Notes_Font)

        self.spin_Notes_FontSize = QSpinBox(self.tab_Notes)
        self.spin_Notes_FontSize.setObjectName(u"spin_Notes_FontSize")
        self.spin_Notes_FontSize.setMinimumSize(QSize(35, 0))
        self.spin_Notes_FontSize.setMinimum(3)
        self.spin_Notes_FontSize.setMaximum(50)
        self.spin_Notes_FontSize.setValue(11)

        self.hlayout_Notes.addWidget(self.spin_Notes_FontSize)

        self.label_NotesColour = QLabel(self.tab_Notes)
        self.label_NotesColour.setObjectName(u"label_NotesColour")
        self.label_NotesColour.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.hlayout_Notes.addWidget(self.label_NotesColour)

        self.combo_Notes_Colour = QComboBox(self.tab_Notes)
        self.combo_Notes_Colour.setObjectName(u"combo_Notes_Colour")
        self.combo_Notes_Colour.setMinimumSize(QSize(140, 0))
        self.combo_Notes_Colour.setMaxVisibleItems(15)

        self.hlayout_Notes.addWidget(self.combo_Notes_Colour)

        self.hSpacer_Notes = QSpacerItem(90, 20, QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Minimum)

        self.hlayout_Notes.addItem(self.hSpacer_Notes)

        self.btn_ConvertToHTML = QPushButton(self.tab_Notes)
        self.btn_ConvertToHTML.setObjectName(u"btn_ConvertToHTML")

        self.hlayout_Notes.addWidget(self.btn_ConvertToHTML)


        self.vlayout_Notes.addLayout(self.hlayout_Notes)

        self.textedit_Notes = QTextEdit(self.tab_Notes)
        self.textedit_Notes.setObjectName(u"textedit_Notes")
        font2 = QFont()
        font2.setPointSize(11)
        self.textedit_Notes.setFont(font2)
        self.textedit_Notes.setLineWidth(0)
        self.textedit_Notes.setLineWrapMode(QTextEdit.NoWrap)

        self.vlayout_Notes.addWidget(self.textedit_Notes)

        self.tab_main.addTab(self.tab_Notes, "")
#if QT_CONFIG(whatsthis)
        self.tab_main.setTabWhatsThis(self.tab_main.indexOf(self.tab_Notes), u"NOTES")
#endif // QT_CONFIG(whatsthis)
        self.tab_Calcs = QWidget()
        self.tab_Calcs.setObjectName(u"tab_Calcs")
        font3 = QFont()
        font3.setFamilies([u"Lucida Sans Typewriter"])
        font3.setPointSize(10)
        self.tab_Calcs.setFont(font3)
        self.tab_main.addTab(self.tab_Calcs, "")
#if QT_CONFIG(whatsthis)
        self.tab_main.setTabWhatsThis(self.tab_main.indexOf(self.tab_Calcs), u"CALCS")
#endif // QT_CONFIG(whatsthis)
        self.tab_Config = QWidget()
        self.tab_Config.setObjectName(u"tab_Config")
        self.hlayout_Config = QHBoxLayout(self.tab_Config)
        self.hlayout_Config.setObjectName(u"hlayout_Config")
        self.hlayout_Config.setContentsMargins(0, 0, 0, 0)
        self.frame_Config = QFrame(self.tab_Config)
        self.frame_Config.setObjectName(u"frame_Config")
        self.grpbox_General = QGroupBox(self.frame_Config)
        self.grpbox_General.setObjectName(u"grpbox_General")
        self.grpbox_General.setGeometry(QRect(2, 2, 304, 214))
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.grpbox_General.sizePolicy().hasHeightForWidth())
        self.grpbox_General.setSizePolicy(sizePolicy5)
        self.grpbox_General.setMinimumSize(QSize(300, 0))
        self.gridLayout_2 = QGridLayout(self.grpbox_General)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.label_ResPenalty = QLabel(self.grpbox_General)
        self.label_ResPenalty.setObjectName(u"label_ResPenalty")
        font4 = QFont()
        font4.setPointSize(8)
        self.label_ResPenalty.setFont(font4)
        self.label_ResPenalty.setLayoutDirection(Qt.LeftToRight)
        self.label_ResPenalty.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.label_ResPenalty, 0, 0, 1, 1)

        self.combo_ResPenalty = QComboBox(self.grpbox_General)
        self.combo_ResPenalty.setObjectName(u"combo_ResPenalty")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.combo_ResPenalty.sizePolicy().hasHeightForWidth())
        self.combo_ResPenalty.setSizePolicy(sizePolicy6)
        self.combo_ResPenalty.setMinimumSize(QSize(130, 0))
        self.combo_ResPenalty.setMaximumSize(QSize(145, 16777215))
        self.combo_ResPenalty.setFont(font4)
        self.combo_ResPenalty.setMinimumContentsLength(60)
        self.combo_ResPenalty.setModelColumn(0)

        self.gridLayout_2.addWidget(self.combo_ResPenalty, 0, 1, 1, 1)

        self.label_Bandits = QLabel(self.grpbox_General)
        self.label_Bandits.setObjectName(u"label_Bandits")
        self.label_Bandits.setFont(font4)
        self.label_Bandits.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.label_Bandits, 1, 0, 1, 1)

        self.combo_Bandits = QComboBox(self.grpbox_General)
        self.combo_Bandits.setObjectName(u"combo_Bandits")
        sizePolicy6.setHeightForWidth(self.combo_Bandits.sizePolicy().hasHeightForWidth())
        self.combo_Bandits.setSizePolicy(sizePolicy6)
        self.combo_Bandits.setMinimumSize(QSize(130, 0))
        self.combo_Bandits.setMaximumSize(QSize(145, 16777215))
        self.combo_Bandits.setFont(font4)
        self.combo_Bandits.setMinimumContentsLength(60)
        self.combo_Bandits.setModelColumn(0)

        self.gridLayout_2.addWidget(self.combo_Bandits, 1, 1, 1, 1)

        self.label_MajorPantheon = QLabel(self.grpbox_General)
        self.label_MajorPantheon.setObjectName(u"label_MajorPantheon")
        self.label_MajorPantheon.setMinimumSize(QSize(0, 0))
        self.label_MajorPantheon.setFont(font4)
        self.label_MajorPantheon.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.label_MajorPantheon, 2, 0, 1, 1)

        self.combo_MajorPantheon = QComboBox(self.grpbox_General)
        self.combo_MajorPantheon.setObjectName(u"combo_MajorPantheon")
        sizePolicy6.setHeightForWidth(self.combo_MajorPantheon.sizePolicy().hasHeightForWidth())
        self.combo_MajorPantheon.setSizePolicy(sizePolicy6)
        self.combo_MajorPantheon.setMinimumSize(QSize(130, 0))
        self.combo_MajorPantheon.setMaximumSize(QSize(145, 16777215))
        self.combo_MajorPantheon.setFont(font4)

        self.gridLayout_2.addWidget(self.combo_MajorPantheon, 2, 1, 1, 1)

        self.label_MinorPantheon = QLabel(self.grpbox_General)
        self.label_MinorPantheon.setObjectName(u"label_MinorPantheon")
        self.label_MinorPantheon.setMinimumSize(QSize(0, 0))
        self.label_MinorPantheon.setFont(font4)
        self.label_MinorPantheon.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.label_MinorPantheon, 3, 0, 1, 1)

        self.combo_MinorPantheon = QComboBox(self.grpbox_General)
        self.combo_MinorPantheon.setObjectName(u"combo_MinorPantheon")
        sizePolicy6.setHeightForWidth(self.combo_MinorPantheon.sizePolicy().hasHeightForWidth())
        self.combo_MinorPantheon.setSizePolicy(sizePolicy6)
        self.combo_MinorPantheon.setMinimumSize(QSize(130, 0))
        self.combo_MinorPantheon.setMaximumSize(QSize(145, 16777215))
        self.combo_MinorPantheon.setFont(font4)

        self.gridLayout_2.addWidget(self.combo_MinorPantheon, 3, 1, 1, 1)

        self.label_EHPUnluckyWorstOf = QLabel(self.grpbox_General)
        self.label_EHPUnluckyWorstOf.setObjectName(u"label_EHPUnluckyWorstOf")
        self.label_EHPUnluckyWorstOf.setMinimumSize(QSize(0, 0))
        self.label_EHPUnluckyWorstOf.setFont(font4)
        self.label_EHPUnluckyWorstOf.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.label_EHPUnluckyWorstOf, 4, 0, 1, 1)

        self.combo_EHPUnluckyWorstOf = QComboBox(self.grpbox_General)
        self.combo_EHPUnluckyWorstOf.setObjectName(u"combo_EHPUnluckyWorstOf")
        sizePolicy6.setHeightForWidth(self.combo_EHPUnluckyWorstOf.sizePolicy().hasHeightForWidth())
        self.combo_EHPUnluckyWorstOf.setSizePolicy(sizePolicy6)
        self.combo_EHPUnluckyWorstOf.setMinimumSize(QSize(130, 0))
        self.combo_EHPUnluckyWorstOf.setMaximumSize(QSize(145, 16777215))
        self.combo_EHPUnluckyWorstOf.setFont(font4)

        self.gridLayout_2.addWidget(self.combo_EHPUnluckyWorstOf, 4, 1, 1, 1)

        self.label_igniteMode = QLabel(self.grpbox_General)
        self.label_igniteMode.setObjectName(u"label_igniteMode")
        self.label_igniteMode.setMinimumSize(QSize(0, 0))
        self.label_igniteMode.setFont(font4)
        self.label_igniteMode.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.label_igniteMode, 5, 0, 1, 1)

        self.combo_igniteMode = QComboBox(self.grpbox_General)
        self.combo_igniteMode.setObjectName(u"combo_igniteMode")
        sizePolicy6.setHeightForWidth(self.combo_igniteMode.sizePolicy().hasHeightForWidth())
        self.combo_igniteMode.setSizePolicy(sizePolicy6)
        self.combo_igniteMode.setMinimumSize(QSize(130, 0))
        self.combo_igniteMode.setMaximumSize(QSize(145, 16777215))
        self.combo_igniteMode.setFont(font4)

        self.gridLayout_2.addWidget(self.combo_igniteMode, 5, 1, 1, 1)

        self.label_IgnoreJewelLimits = QLabel(self.grpbox_General)
        self.label_IgnoreJewelLimits.setObjectName(u"label_IgnoreJewelLimits")
        self.label_IgnoreJewelLimits.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_2.addWidget(self.label_IgnoreJewelLimits, 6, 0, 1, 1)

        self.check_IgnoreJewelLimits = QCheckBox(self.grpbox_General)
        self.check_IgnoreJewelLimits.setObjectName(u"check_IgnoreJewelLimits")
        sizePolicy6.setHeightForWidth(self.check_IgnoreJewelLimits.sizePolicy().hasHeightForWidth())
        self.check_IgnoreJewelLimits.setSizePolicy(sizePolicy6)
        self.check_IgnoreJewelLimits.setMinimumSize(QSize(130, 0))
        self.check_IgnoreJewelLimits.setMaximumSize(QSize(145, 16777215))

        self.gridLayout_2.addWidget(self.check_IgnoreJewelLimits, 6, 1, 1, 1)

        self.grpbox_SkillOptions = QGroupBox(self.frame_Config)
        self.grpbox_SkillOptions.setObjectName(u"grpbox_SkillOptions")
        self.grpbox_SkillOptions.setGeometry(QRect(308, 2, 300, 300))
        sizePolicy6.setHeightForWidth(self.grpbox_SkillOptions.sizePolicy().hasHeightForWidth())
        self.grpbox_SkillOptions.setSizePolicy(sizePolicy6)
        self.grpbox_SkillOptions.setMinimumSize(QSize(300, 300))
        self.grpbox_Combat = QGroupBox(self.frame_Config)
        self.grpbox_Combat.setObjectName(u"grpbox_Combat")
        self.grpbox_Combat.setGeometry(QRect(0, 220, 300, 494))
        sizePolicy6.setHeightForWidth(self.grpbox_Combat.sizePolicy().hasHeightForWidth())
        self.grpbox_Combat.setSizePolicy(sizePolicy6)
        self.grpbox_Combat.setMinimumSize(QSize(300, 300))
        self.gridLayout = QGridLayout(self.grpbox_Combat)
        self.gridLayout.setObjectName(u"gridLayout")
        self.label_PowerCharges = QLabel(self.grpbox_Combat)
        self.label_PowerCharges.setObjectName(u"label_PowerCharges")
        self.label_PowerCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_PowerCharges, 0, 0, 1, 1)

        self.check_PowerCharges = QCheckBox(self.grpbox_Combat)
        self.check_PowerCharges.setObjectName(u"check_PowerCharges")
        sizePolicy6.setHeightForWidth(self.check_PowerCharges.sizePolicy().hasHeightForWidth())
        self.check_PowerCharges.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.check_PowerCharges, 0, 1, 1, 1)

        self.label_NumPowerCharges = QLabel(self.grpbox_Combat)
        self.label_NumPowerCharges.setObjectName(u"label_NumPowerCharges")
        self.label_NumPowerCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_NumPowerCharges, 1, 0, 1, 1)

        self.spin_NumPowerCharges = QSpinBox(self.grpbox_Combat)
        self.spin_NumPowerCharges.setObjectName(u"spin_NumPowerCharges")
        sizePolicy6.setHeightForWidth(self.spin_NumPowerCharges.sizePolicy().hasHeightForWidth())
        self.spin_NumPowerCharges.setSizePolicy(sizePolicy6)
        self.spin_NumPowerCharges.setValue(3)

        self.gridLayout.addWidget(self.spin_NumPowerCharges, 1, 1, 1, 1)

        self.label_FrenzyCharges = QLabel(self.grpbox_Combat)
        self.label_FrenzyCharges.setObjectName(u"label_FrenzyCharges")
        self.label_FrenzyCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_FrenzyCharges, 2, 0, 1, 1)

        self.check_FrenzyCharges = QCheckBox(self.grpbox_Combat)
        self.check_FrenzyCharges.setObjectName(u"check_FrenzyCharges")
        sizePolicy6.setHeightForWidth(self.check_FrenzyCharges.sizePolicy().hasHeightForWidth())
        self.check_FrenzyCharges.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.check_FrenzyCharges, 2, 1, 1, 1)

        self.label_NumFrenzyCharges = QLabel(self.grpbox_Combat)
        self.label_NumFrenzyCharges.setObjectName(u"label_NumFrenzyCharges")
        self.label_NumFrenzyCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_NumFrenzyCharges, 3, 0, 1, 1)

        self.spin_NumFrenzyCharges = QSpinBox(self.grpbox_Combat)
        self.spin_NumFrenzyCharges.setObjectName(u"spin_NumFrenzyCharges")
        sizePolicy6.setHeightForWidth(self.spin_NumFrenzyCharges.sizePolicy().hasHeightForWidth())
        self.spin_NumFrenzyCharges.setSizePolicy(sizePolicy6)
        self.spin_NumFrenzyCharges.setValue(3)

        self.gridLayout.addWidget(self.spin_NumFrenzyCharges, 3, 1, 1, 1)

        self.label_EnduranceCharges = QLabel(self.grpbox_Combat)
        self.label_EnduranceCharges.setObjectName(u"label_EnduranceCharges")
        self.label_EnduranceCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_EnduranceCharges, 4, 0, 1, 1)

        self.check_EnduranceCharges = QCheckBox(self.grpbox_Combat)
        self.check_EnduranceCharges.setObjectName(u"check_EnduranceCharges")
        sizePolicy6.setHeightForWidth(self.check_EnduranceCharges.sizePolicy().hasHeightForWidth())
        self.check_EnduranceCharges.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.check_EnduranceCharges, 4, 1, 1, 1)

        self.label_NumEnduranceCharges = QLabel(self.grpbox_Combat)
        self.label_NumEnduranceCharges.setObjectName(u"label_NumEnduranceCharges")
        self.label_NumEnduranceCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_NumEnduranceCharges, 5, 0, 1, 1)

        self.spin_NumEnduranceCharges = QSpinBox(self.grpbox_Combat)
        self.spin_NumEnduranceCharges.setObjectName(u"spin_NumEnduranceCharges")
        sizePolicy6.setHeightForWidth(self.spin_NumEnduranceCharges.sizePolicy().hasHeightForWidth())
        self.spin_NumEnduranceCharges.setSizePolicy(sizePolicy6)
        self.spin_NumEnduranceCharges.setValue(3)

        self.gridLayout.addWidget(self.spin_NumEnduranceCharges, 5, 1, 1, 1)

        self.label_SiphoningCharges = QLabel(self.grpbox_Combat)
        self.label_SiphoningCharges.setObjectName(u"label_SiphoningCharges")
        self.label_SiphoningCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_SiphoningCharges, 6, 0, 1, 1)

        self.check_SiphoningCharges = QCheckBox(self.grpbox_Combat)
        self.check_SiphoningCharges.setObjectName(u"check_SiphoningCharges")
        sizePolicy6.setHeightForWidth(self.check_SiphoningCharges.sizePolicy().hasHeightForWidth())
        self.check_SiphoningCharges.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.check_SiphoningCharges, 6, 1, 1, 1)

        self.label_NumSiphoningCharges = QLabel(self.grpbox_Combat)
        self.label_NumSiphoningCharges.setObjectName(u"label_NumSiphoningCharges")
        self.label_NumSiphoningCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_NumSiphoningCharges, 7, 0, 1, 1)

        self.spin_NumSiphoningCharges = QSpinBox(self.grpbox_Combat)
        self.spin_NumSiphoningCharges.setObjectName(u"spin_NumSiphoningCharges")
        sizePolicy6.setHeightForWidth(self.spin_NumSiphoningCharges.sizePolicy().hasHeightForWidth())
        self.spin_NumSiphoningCharges.setSizePolicy(sizePolicy6)
        self.spin_NumSiphoningCharges.setValue(3)

        self.gridLayout.addWidget(self.spin_NumSiphoningCharges, 7, 1, 1, 1)

        self.label_ChallengerCharges = QLabel(self.grpbox_Combat)
        self.label_ChallengerCharges.setObjectName(u"label_ChallengerCharges")
        self.label_ChallengerCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_ChallengerCharges, 8, 0, 1, 1)

        self.check_ChallengerCharges = QCheckBox(self.grpbox_Combat)
        self.check_ChallengerCharges.setObjectName(u"check_ChallengerCharges")
        sizePolicy6.setHeightForWidth(self.check_ChallengerCharges.sizePolicy().hasHeightForWidth())
        self.check_ChallengerCharges.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.check_ChallengerCharges, 8, 1, 1, 1)

        self.label_NumChallengerCharges = QLabel(self.grpbox_Combat)
        self.label_NumChallengerCharges.setObjectName(u"label_NumChallengerCharges")
        self.label_NumChallengerCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_NumChallengerCharges, 9, 0, 1, 1)

        self.spin_NumChallengerCharges = QSpinBox(self.grpbox_Combat)
        self.spin_NumChallengerCharges.setObjectName(u"spin_NumChallengerCharges")
        sizePolicy6.setHeightForWidth(self.spin_NumChallengerCharges.sizePolicy().hasHeightForWidth())
        self.spin_NumChallengerCharges.setSizePolicy(sizePolicy6)
        self.spin_NumChallengerCharges.setValue(3)

        self.gridLayout.addWidget(self.spin_NumChallengerCharges, 9, 1, 1, 1)

        self.label_BlitzCharges = QLabel(self.grpbox_Combat)
        self.label_BlitzCharges.setObjectName(u"label_BlitzCharges")
        self.label_BlitzCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_BlitzCharges, 10, 0, 1, 1)

        self.check_BlitzCharges = QCheckBox(self.grpbox_Combat)
        self.check_BlitzCharges.setObjectName(u"check_BlitzCharges")
        sizePolicy6.setHeightForWidth(self.check_BlitzCharges.sizePolicy().hasHeightForWidth())
        self.check_BlitzCharges.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.check_BlitzCharges, 10, 1, 1, 1)

        self.label_NumBlitzCharges = QLabel(self.grpbox_Combat)
        self.label_NumBlitzCharges.setObjectName(u"label_NumBlitzCharges")
        self.label_NumBlitzCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_NumBlitzCharges, 11, 0, 1, 1)

        self.spin_NumBlitzCharges = QSpinBox(self.grpbox_Combat)
        self.spin_NumBlitzCharges.setObjectName(u"spin_NumBlitzCharges")
        sizePolicy6.setHeightForWidth(self.spin_NumBlitzCharges.sizePolicy().hasHeightForWidth())
        self.spin_NumBlitzCharges.setSizePolicy(sizePolicy6)
        self.spin_NumBlitzCharges.setValue(3)

        self.gridLayout.addWidget(self.spin_NumBlitzCharges, 11, 1, 2, 1)

        self.label_GhostCharges = QLabel(self.grpbox_Combat)
        self.label_GhostCharges.setObjectName(u"label_GhostCharges")
        self.label_GhostCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_GhostCharges, 12, 0, 2, 1)

        self.check_GhostCharges = QCheckBox(self.grpbox_Combat)
        self.check_GhostCharges.setObjectName(u"check_GhostCharges")
        sizePolicy6.setHeightForWidth(self.check_GhostCharges.sizePolicy().hasHeightForWidth())
        self.check_GhostCharges.setSizePolicy(sizePolicy6)

        self.gridLayout.addWidget(self.check_GhostCharges, 13, 1, 1, 1)

        self.label_NumGhostCharges = QLabel(self.grpbox_Combat)
        self.label_NumGhostCharges.setObjectName(u"label_NumGhostCharges")
        self.label_NumGhostCharges.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_NumGhostCharges, 14, 0, 1, 1)

        self.spin_NumGhostCharges = QSpinBox(self.grpbox_Combat)
        self.spin_NumGhostCharges.setObjectName(u"spin_NumGhostCharges")
        sizePolicy6.setHeightForWidth(self.spin_NumGhostCharges.sizePolicy().hasHeightForWidth())
        self.spin_NumGhostCharges.setSizePolicy(sizePolicy6)
        self.spin_NumGhostCharges.setValue(3)

        self.gridLayout.addWidget(self.spin_NumGhostCharges, 14, 1, 1, 1)

        self.verticalSpacer_2 = QSpacerItem(20, 111, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer_2, 15, 0, 1, 1)

        self.grpbox_5 = QGroupBox(self.frame_Config)
        self.grpbox_5.setObjectName(u"grpbox_5")
        self.grpbox_5.setGeometry(QRect(614, 2, 300, 300))
        sizePolicy6.setHeightForWidth(self.grpbox_5.sizePolicy().hasHeightForWidth())
        self.grpbox_5.setSizePolicy(sizePolicy6)
        self.grpbox_5.setMinimumSize(QSize(300, 300))
        self.grpbox_EffectiveDPS = QGroupBox(self.frame_Config)
        self.grpbox_EffectiveDPS.setObjectName(u"grpbox_EffectiveDPS")
        self.grpbox_EffectiveDPS.setGeometry(QRect(308, 308, 300, 300))
        sizePolicy6.setHeightForWidth(self.grpbox_EffectiveDPS.sizePolicy().hasHeightForWidth())
        self.grpbox_EffectiveDPS.setSizePolicy(sizePolicy6)
        self.grpbox_EffectiveDPS.setMinimumSize(QSize(300, 300))
        self.grpbox_CustomModifiers = QGroupBox(self.frame_Config)
        self.grpbox_CustomModifiers.setObjectName(u"grpbox_CustomModifiers")
        self.grpbox_CustomModifiers.setGeometry(QRect(614, 308, 300, 300))
        sizePolicy6.setHeightForWidth(self.grpbox_CustomModifiers.sizePolicy().hasHeightForWidth())
        self.grpbox_CustomModifiers.setSizePolicy(sizePolicy6)
        self.grpbox_CustomModifiers.setMinimumSize(QSize(300, 300))
        self.horizontalLayout_3 = QHBoxLayout(self.grpbox_CustomModifiers)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 9, 0, 0)
        self.textedit_CustomModifiers = QPlainTextEdit(self.grpbox_CustomModifiers)
        self.textedit_CustomModifiers.setObjectName(u"textedit_CustomModifiers")

        self.horizontalLayout_3.addWidget(self.textedit_CustomModifiers)


        self.hlayout_Config.addWidget(self.frame_Config)

        self.tab_main.addTab(self.tab_Config, "")
#if QT_CONFIG(whatsthis)
        self.tab_main.setTabWhatsThis(self.tab_main.indexOf(self.tab_Config), u"CONFIG")
#endif // QT_CONFIG(whatsthis)
        self.splitter_MainWindow.addWidget(self.tab_main)

        self.horizontalLayout_5.addWidget(self.splitter_MainWindow)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.hlayout_MainWindow.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar_MainWindow = QMenuBar(MainWindow)
        self.menubar_MainWindow.setObjectName(u"menubar_MainWindow")
        self.menubar_MainWindow.setGeometry(QRect(0, 0, 1421, 22))
        self.menu_Builds = QMenu(self.menubar_MainWindow)
        self.menu_Builds.setObjectName(u"menu_Builds")
        self.menu_Settings = QMenu(self.menubar_MainWindow)
        self.menu_Settings.setObjectName(u"menu_Settings")
        self.menu_Theme = QMenu(self.menu_Settings)
        self.menu_Theme.setObjectName(u"menu_Theme")
        icon9 = QIcon()
        icon9.addFile(u":/Art/Icons/yin-yang.png", QSize(), QIcon.Normal, QIcon.Off)
        self.menu_Theme.setIcon(icon9)
        MainWindow.setMenuBar(self.menubar_MainWindow)
        self.statusbar_MainWindow = QStatusBar(MainWindow)
        self.statusbar_MainWindow.setObjectName(u"statusbar_MainWindow")
        MainWindow.setStatusBar(self.statusbar_MainWindow)
        self.toolbar_MainWindow = QToolBar(MainWindow)
        self.toolbar_MainWindow.setObjectName(u"toolbar_MainWindow")
        self.toolbar_MainWindow.setAllowedAreas(Qt.BottomToolBarArea|Qt.TopToolBarArea)
        self.toolbar_MainWindow.setFloatable(False)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolbar_MainWindow)
#if QT_CONFIG(shortcut)
        self.label_DefaultGemQuality.setBuddy(self.spin_DefaultGemQuality)
        self.label_ShowSupportGems.setBuddy(self.combo_ShowSupportGems)
        self.label_DefaultGemLevel.setBuddy(self.combo_ShowSupportGems)
        self.label_ItemSet.setBuddy(self.combo_ItemSet)
        self.label_ItemsPassiveTree.setBuddy(self.combo_ItemsManageTree)
        self.label_ItemsSearch.setBuddy(self.lineedit_ItemsSearch)
        self.label_ItemsImportFrom.setBuddy(self.combo_ItemsImportFrom)
        self.label_ImportItemsSearch.setBuddy(self.lineedit_ItemsImportSearch)
        self.label_NotesColour.setBuddy(self.combo_Notes_Colour)
        self.label_ResPenalty.setBuddy(self.combo_ResPenalty)
        self.label_Bandits.setBuddy(self.combo_Bandits)
        self.label_MajorPantheon.setBuddy(self.combo_MajorPantheon)
        self.label_MinorPantheon.setBuddy(self.combo_MinorPantheon)
        self.label_EHPUnluckyWorstOf.setBuddy(self.combo_MinorPantheon)
        self.label_igniteMode.setBuddy(self.combo_MinorPantheon)
        self.label_IgnoreJewelLimits.setBuddy(self.check_IgnoreJewelLimits)
        self.label_PowerCharges.setBuddy(self.check_PowerCharges)
        self.label_NumPowerCharges.setBuddy(self.spin_NumPowerCharges)
        self.label_FrenzyCharges.setBuddy(self.check_FrenzyCharges)
        self.label_NumFrenzyCharges.setBuddy(self.spin_NumFrenzyCharges)
        self.label_EnduranceCharges.setBuddy(self.check_EnduranceCharges)
        self.label_NumEnduranceCharges.setBuddy(self.spin_NumEnduranceCharges)
        self.label_SiphoningCharges.setBuddy(self.check_SiphoningCharges)
        self.label_NumSiphoningCharges.setBuddy(self.spin_NumSiphoningCharges)
        self.label_ChallengerCharges.setBuddy(self.check_ChallengerCharges)
        self.label_NumChallengerCharges.setBuddy(self.spin_NumChallengerCharges)
        self.label_BlitzCharges.setBuddy(self.check_BlitzCharges)
        self.label_NumBlitzCharges.setBuddy(self.spin_NumBlitzCharges)
        self.label_GhostCharges.setBuddy(self.check_GhostCharges)
        self.label_NumGhostCharges.setBuddy(self.spin_NumGhostCharges)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.scrollArea, self.combo_MainSkill)
        QWidget.setTabOrder(self.combo_MainSkill, self.combo_MainSkillActive)
        QWidget.setTabOrder(self.combo_MainSkillActive, self.combo_ResPenalty)
        QWidget.setTabOrder(self.combo_ResPenalty, self.combo_Bandits)
        QWidget.setTabOrder(self.combo_Bandits, self.combo_MajorPantheon)
        QWidget.setTabOrder(self.combo_MajorPantheon, self.combo_MinorPantheon)
        QWidget.setTabOrder(self.combo_MinorPantheon, self.textedit_Notes)
        QWidget.setTabOrder(self.textedit_Notes, self.combo_Notes_Font)
        QWidget.setTabOrder(self.combo_Notes_Font, self.combo_Notes_Colour)
        QWidget.setTabOrder(self.combo_Notes_Colour, self.spin_Notes_FontSize)
        QWidget.setTabOrder(self.spin_Notes_FontSize, self.graphicsView_PlaceHolder)

        self.menubar_MainWindow.addAction(self.menu_Builds.menuAction())
        self.menubar_MainWindow.addAction(self.menu_Settings.menuAction())
        self.menu_Builds.addAction(self.action_New)
        self.menu_Builds.addAction(self.action_Open)
        self.menu_Builds.addAction(self.action_Save)
        self.menu_Builds.addAction(self.action_SaveAs)
        self.menu_Builds.addAction(self.action_Import)
        self.menu_Builds.addAction(self.action_Export)
        self.menu_Builds.addSeparator()
        self.menu_Builds.addAction(self.action_Exit)
        self.menu_Builds.addSeparator()
        self.menu_Settings.addAction(self.action_Settings)
        self.menu_Settings.addAction(self.menu_Theme.menuAction())
        self.toolbar_MainWindow.addAction(self.action_New)
        self.toolbar_MainWindow.addAction(self.action_Open)
        self.toolbar_MainWindow.addAction(self.action_Save)
        self.toolbar_MainWindow.addAction(self.action_Import)
        self.toolbar_MainWindow.addAction(self.action_Export)
        self.toolbar_MainWindow.addAction(self.action_Settings)
        self.toolbar_MainWindow.addSeparator()
        self.toolbar_MainWindow.addAction(self.action_ManageTrees)

        self.retranslateUi(MainWindow)
        self.action_Exit.triggered.connect(MainWindow.close)
        self.check_PowerCharges.toggled.connect(self.label_NumPowerCharges.setVisible)
        self.check_PowerCharges.toggled.connect(self.spin_NumPowerCharges.setVisible)
        self.check_FrenzyCharges.toggled.connect(self.label_NumFrenzyCharges.setVisible)
        self.check_FrenzyCharges.toggled.connect(self.spin_NumFrenzyCharges.setVisible)
        self.check_EnduranceCharges.toggled.connect(self.label_NumEnduranceCharges.setVisible)
        self.check_EnduranceCharges.toggled.connect(self.spin_NumEnduranceCharges.setVisible)
        self.check_SiphoningCharges.toggled.connect(self.label_NumSiphoningCharges.setVisible)
        self.check_SiphoningCharges.toggled.connect(self.spin_NumSiphoningCharges.setVisible)
        self.check_ChallengerCharges.toggled.connect(self.label_NumChallengerCharges.setVisible)
        self.check_ChallengerCharges.toggled.connect(self.spin_NumChallengerCharges.setVisible)
        self.check_BlitzCharges.toggled.connect(self.label_NumBlitzCharges.setVisible)
        self.check_BlitzCharges.toggled.connect(self.spin_NumBlitzCharges.setVisible)
        self.check_GhostCharges.toggled.connect(self.label_NumGhostCharges.setVisible)
        self.check_GhostCharges.toggled.connect(self.spin_NumGhostCharges.setVisible)

        self.tab_main.setCurrentIndex(3)
        self.list_SocketGroups.setCurrentRow(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_New.setText(QCoreApplication.translate("MainWindow", u"&New", None))
#if QT_CONFIG(tooltip)
        self.action_New.setToolTip(QCoreApplication.translate("MainWindow", u"Start a new build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_New.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_Save.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
#if QT_CONFIG(tooltip)
        self.action_Save.setToolTip(QCoreApplication.translate("MainWindow", u"Save this build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Save.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_Exit.setText(QCoreApplication.translate("MainWindow", u"E&xit", None))
#if QT_CONFIG(tooltip)
        self.action_Exit.setToolTip(QCoreApplication.translate("MainWindow", u"Exit Path of Building", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Exit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_Open.setText(QCoreApplication.translate("MainWindow", u"&Open", None))
#if QT_CONFIG(tooltip)
        self.action_Open.setToolTip(QCoreApplication.translate("MainWindow", u"Open a build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Open.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_ManageTrees.setText(QCoreApplication.translate("MainWindow", u"Manage Trees", None))
#if QT_CONFIG(shortcut)
        self.action_ManageTrees.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.action_Settings.setText(QCoreApplication.translate("MainWindow", u"&Settings ...", None))
#if QT_CONFIG(tooltip)
        self.action_Settings.setToolTip(QCoreApplication.translate("MainWindow", u"Open Settings diaog", None))
#endif // QT_CONFIG(tooltip)
        self.action_Import.setText(QCoreApplication.translate("MainWindow", u"&Import ...", None))
#if QT_CONFIG(tooltip)
        self.action_Import.setToolTip(QCoreApplication.translate("MainWindow", u"Import a build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Import.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.action_Export.setText(QCoreApplication.translate("MainWindow", u"Export ...", None))
#if QT_CONFIG(tooltip)
        self.action_Export.setToolTip(QCoreApplication.translate("MainWindow", u"Export a build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Export.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.action_SaveAs.setText(QCoreApplication.translate("MainWindow", u"Save &As", None))
#if QT_CONFIG(tooltip)
        self.action_SaveAs.setToolTip(QCoreApplication.translate("MainWindow", u"Save this build", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_SaveAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.combo_MainSkill.setPlaceholderText(QCoreApplication.translate("MainWindow", u"<empty>", None))
        self.combo_MainSkillActive.setPlaceholderText(QCoreApplication.translate("MainWindow", u"<empty>", None))
        self.label_MainSkill.setText(QCoreApplication.translate("MainWindow", u"Main Skill:", None))
#if QT_CONFIG(accessibility)
        self.tab_main.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_Tree), QCoreApplication.translate("MainWindow", u"&Tree", None))
        self.label_Usage_Hints.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><span style=\" font-size:9pt;\">Usage Hints:<br>- You can copy/paste socket groups using Ctrl-C and Ctrl-V.<br>- Ctrl-Left click to enable and disable socket groups.<br>- Ctrl-Right click to include/exclude in FullDPS calculations.<br>- Right click to set as the Main skill group.</span></body></html>", None))
        self.group_SkillTabLeft.setTitle(QCoreApplication.translate("MainWindow", u"Gem Options", None))
        self.label_DefaultGemQuality.setText(QCoreApplication.translate("MainWindow", u"Default Gem &Quality", None))
        self.check_SortByDPS.setText(QCoreApplication.translate("MainWindow", u"Sort Gems by &DPS", None))
        self.check_ShowGemQualityVariants.setText(QCoreApplication.translate("MainWindow", u"Show Gem Quality &Variants", None))
        self.label_ShowSupportGems.setText(QCoreApplication.translate("MainWindow", u"Sho&w Support Gems", None))
        self.label_DefaultGemLevel.setText(QCoreApplication.translate("MainWindow", u"Default Gem &Level", None))
        self.combo_SkillSet.setPlaceholderText(QCoreApplication.translate("MainWindow", u"<empty>", None))
        self.btn_NewSocketGroup.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.label_SocketGroups.setText(QCoreApplication.translate("MainWindow", u"Socket Groups:", None))
        self.btn_DeleteAllSocketGroups.setText(QCoreApplication.translate("MainWindow", u"Delete All", None))
        self.label_SkillSet.setText(QCoreApplication.translate("MainWindow", u"Skill Set:", None))
        self.btn_SkillsManage.setText(QCoreApplication.translate("MainWindow", u"&Manage ...", None))
#if QT_CONFIG(shortcut)
        self.btn_SkillsManage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.btn_DeleteSocketGroup.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.label_GemName.setText(QCoreApplication.translate("MainWindow", u"Gem Name:", None))
        self.combo_SocketedIn.setItemText(0, QCoreApplication.translate("MainWindow", u"None", None))
        self.combo_SocketedIn.setItemText(1, QCoreApplication.translate("MainWindow", u"Weapon 1", None))
        self.combo_SocketedIn.setItemText(2, QCoreApplication.translate("MainWindow", u"Weapon 2", None))
        self.combo_SocketedIn.setItemText(3, QCoreApplication.translate("MainWindow", u"Weapon 1 Swap", None))
        self.combo_SocketedIn.setItemText(4, QCoreApplication.translate("MainWindow", u"Weapon 2 Swap", None))
        self.combo_SocketedIn.setItemText(5, QCoreApplication.translate("MainWindow", u"Helmet", None))
        self.combo_SocketedIn.setItemText(6, QCoreApplication.translate("MainWindow", u"Body Armour", None))
        self.combo_SocketedIn.setItemText(7, QCoreApplication.translate("MainWindow", u"Gloves", None))
        self.combo_SocketedIn.setItemText(8, QCoreApplication.translate("MainWindow", u"Boots", None))
        self.combo_SocketedIn.setItemText(9, QCoreApplication.translate("MainWindow", u"Amulet", None))
        self.combo_SocketedIn.setItemText(10, QCoreApplication.translate("MainWindow", u"Ring 1", None))
        self.combo_SocketedIn.setItemText(11, QCoreApplication.translate("MainWindow", u"Ring 2", None))
        self.combo_SocketedIn.setItemText(12, QCoreApplication.translate("MainWindow", u"Belt", None))

        self.combo_SocketedIn.setPlaceholderText(QCoreApplication.translate("MainWindow", u"<empty>", None))
        self.label_Variant.setText(QCoreApplication.translate("MainWindow", u"Variant", None))
        self.label_SkillLabel.setText(QCoreApplication.translate("MainWindow", u"Skill Label:", None))
        self.label_Enabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.label_Quality.setText(QCoreApplication.translate("MainWindow", u"Quality", None))
        self.label_Count.setText(QCoreApplication.translate("MainWindow", u"Count", None))
        self.label_SocketedIn.setText(QCoreApplication.translate("MainWindow", u"Socketed In:", None))
        self.label_Level.setText(QCoreApplication.translate("MainWindow", u"Level:", None))
        self.check_SocketGroupEnabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.check_SocketGroup_FullDPS.setText(QCoreApplication.translate("MainWindow", u"Include in Full DPS", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_Skills), QCoreApplication.translate("MainWindow", u"S&kills", None))
        self.label_ItemSet.setText(QCoreApplication.translate("MainWindow", u"Item &Set:", None))
        self.combo_ItemSet.setPlaceholderText(QCoreApplication.translate("MainWindow", u"<empty>", None))
        self.btn_ManageItemSet.setText(QCoreApplication.translate("MainWindow", u"&Manage ...", None))
#if QT_CONFIG(shortcut)
        self.btn_ManageItemSet.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.label_EquippedItems.setText(QCoreApplication.translate("MainWindow", u"Equipped Items:", None))
        self.btn_WeaponSwap.setText(QCoreApplication.translate("MainWindow", u"Show Alt Weapons", None))
#if QT_CONFIG(shortcut)
        self.btn_WeaponSwap.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+X", None))
#endif // QT_CONFIG(shortcut)
        self.label_SocketedJewels.setText(QCoreApplication.translate("MainWindow", u"Socketed Jewels:", None))
        self.label_ItemsPassiveTree.setText(QCoreApplication.translate("MainWindow", u"Passive Tree:", None))
        self.btn_ItemsManageTree.setText(QCoreApplication.translate("MainWindow", u"Manag&e ...", None))
#if QT_CONFIG(shortcut)
        self.btn_ItemsManageTree.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+X", None))
#endif // QT_CONFIG(shortcut)
        self.label_AllItems.setText(QCoreApplication.translate("MainWindow", u"All Items", None))
        self.btn_SortItems.setText(QCoreApplication.translate("MainWindow", u"Sort", None))
        self.btn_DeleteAllItems.setText(QCoreApplication.translate("MainWindow", u"Delete All", None))
        self.btn_DeleteItem.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.btn_DeleteUnusedItems.setText(QCoreApplication.translate("MainWindow", u"Delete Unused", None))
        self.label_ItemsSearch.setText(QCoreApplication.translate("MainWindow", u"&Search:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Double-click an item from one of the lists, or copy and paste an item from in game (hover over the item and Ctrl+C) to view or edit the item and add it to your build. You can also clone an item within Path of Building by copying and pasting it with Ctrl+C and Ctrl+V.\n"
"\n"
"You can Control + Click an item to equip it, or drag it onto the slot.  This will also add it to your build if it's from the unique/template list.\n"
"\n"
"If there's 2 slots an item can go in, holding Shift will put it in the second.", None))
        self.label_ItemsImportFrom.setText(QCoreApplication.translate("MainWindow", u"Import from:", None))
        self.combo_ItemsImportFrom.setItemText(0, QCoreApplication.translate("MainWindow", u"Uniques", None))
        self.combo_ItemsImportFrom.setItemText(1, QCoreApplication.translate("MainWindow", u"Rare Templates", None))

        self.combo_ItemsImportSlot.setItemText(0, QCoreApplication.translate("MainWindow", u"Any Slot", None))
        self.combo_ItemsImportSlot.setItemText(1, QCoreApplication.translate("MainWindow", u"Weapon 1", None))
        self.combo_ItemsImportSlot.setItemText(2, QCoreApplication.translate("MainWindow", u"Weapon 2", None))
        self.combo_ItemsImportSlot.setItemText(3, QCoreApplication.translate("MainWindow", u"Belt", None))
        self.combo_ItemsImportSlot.setItemText(4, QCoreApplication.translate("MainWindow", u"Body Armour", None))
        self.combo_ItemsImportSlot.setItemText(5, QCoreApplication.translate("MainWindow", u"Boots", None))
        self.combo_ItemsImportSlot.setItemText(6, QCoreApplication.translate("MainWindow", u"Gloves", None))
        self.combo_ItemsImportSlot.setItemText(7, QCoreApplication.translate("MainWindow", u"Helmet", None))
        self.combo_ItemsImportSlot.setItemText(8, QCoreApplication.translate("MainWindow", u"Amulet", None))
        self.combo_ItemsImportSlot.setItemText(9, QCoreApplication.translate("MainWindow", u"Ring", None))
        self.combo_ItemsImportSlot.setItemText(10, QCoreApplication.translate("MainWindow", u"Jewel", None))
        self.combo_ItemsImportSlot.setItemText(11, QCoreApplication.translate("MainWindow", u"Flask", None))

        self.combo_ItemsImportType.setItemText(0, QCoreApplication.translate("MainWindow", u"Any Type", None))

        self.combo_ItemsImportSort.setItemText(0, QCoreApplication.translate("MainWindow", u"Sort by Name", None))

        self.combo_ItemsImportLeague.setItemText(0, QCoreApplication.translate("MainWindow", u"Any League", None))
        self.combo_ItemsImportLeague.setItemText(1, QCoreApplication.translate("MainWindow", u"No League", None))

        self.combo_ItemsImportRequirements.setItemText(0, QCoreApplication.translate("MainWindow", u"Any requirements", None))
        self.combo_ItemsImportRequirements.setItemText(1, QCoreApplication.translate("MainWindow", u"Current level", None))
        self.combo_ItemsImportRequirements.setItemText(2, QCoreApplication.translate("MainWindow", u"Current attributes", None))
        self.combo_ItemsImportRequirements.setItemText(3, QCoreApplication.translate("MainWindow", u"Current useable", None))

        self.combo_ItemsImportSource.setItemText(0, QCoreApplication.translate("MainWindow", u"Any Source", None))
        self.combo_ItemsImportSource.setItemText(1, QCoreApplication.translate("MainWindow", u"Obtainable", None))
        self.combo_ItemsImportSource.setItemText(2, QCoreApplication.translate("MainWindow", u"Unobtainable", None))
        self.combo_ItemsImportSource.setItemText(3, QCoreApplication.translate("MainWindow", u"Vendor Recipe", None))
        self.combo_ItemsImportSource.setItemText(4, QCoreApplication.translate("MainWindow", u"Upgraded", None))
        self.combo_ItemsImportSource.setItemText(5, QCoreApplication.translate("MainWindow", u"Boss Item", None))
        self.combo_ItemsImportSource.setItemText(6, QCoreApplication.translate("MainWindow", u"Corruption", None))

        self.label_ImportItemsSearch.setText(QCoreApplication.translate("MainWindow", u"Searc&h:", None))
        self.combo_ItemsImportSearchSource.setItemText(0, QCoreApplication.translate("MainWindow", u"Anywhere", None))
        self.combo_ItemsImportSearchSource.setItemText(1, QCoreApplication.translate("MainWindow", u"Names", None))
        self.combo_ItemsImportSearchSource.setItemText(2, QCoreApplication.translate("MainWindow", u"Modifiers", None))

        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_Items), QCoreApplication.translate("MainWindow", u"&Item", None))
#if QT_CONFIG(whatsthis)
        self.tab_main.setTabWhatsThis(self.tab_main.indexOf(self.tab_Items), QCoreApplication.translate("MainWindow", u"ITEMS", None))
#endif // QT_CONFIG(whatsthis)
        self.combo_Notes_Font.setCurrentText(QCoreApplication.translate("MainWindow", u"Noto Sans", None))
        self.label_NotesColour.setText(QCoreApplication.translate("MainWindow", u"&Colour:", None))
        self.btn_ConvertToHTML.setText(QCoreApplication.translate("MainWindow", u"Convert to HTML", None))
        self.textedit_Notes.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_Notes), QCoreApplication.translate("MainWindow", u"&Notes", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_Calcs), QCoreApplication.translate("MainWindow", u"C&alcs", None))
        self.grpbox_General.setTitle(QCoreApplication.translate("MainWindow", u"General", None))
        self.label_ResPenalty.setText(QCoreApplication.translate("MainWindow", u"&Resistance Penalty:", None))
        self.combo_ResPenalty.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make a Selection", None))
        self.label_Bandits.setText(QCoreApplication.translate("MainWindow", u"&Bandits:", None))
        self.combo_Bandits.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make a Selection", None))
        self.label_MajorPantheon.setText(QCoreApplication.translate("MainWindow", u"Ma&jor God:", None))
        self.combo_MajorPantheon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make a Selection", None))
        self.label_MinorPantheon.setText(QCoreApplication.translate("MainWindow", u"Min&or God:", None))
        self.combo_MinorPantheon.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make a Selection", None))
#if QT_CONFIG(tooltip)
        self.label_EHPUnluckyWorstOf.setToolTip(QCoreApplication.translate("MainWindow", u"Controls how the base damage for applying Ailments is calculated:\n"
"    Average: damage is based on the average application, including both crits and non-crits\n"
"    Crits Only: damage is based solely on Ailments inflicted with crits", None))
#endif // QT_CONFIG(tooltip)
        self.label_EHPUnluckyWorstOf.setText(QCoreApplication.translate("MainWindow", u"Ailment calculation mode:", None))
#if QT_CONFIG(tooltip)
        self.combo_EHPUnluckyWorstOf.setToolTip(QCoreApplication.translate("MainWindow", u"Controls how the base damage for applying Ailments is calculated:\n"
"    Average: damage is based on the average application, including both crits and non-crits\n"
"    Crits Only: damage is based solely on Ailments inflicted with crits", None))
#endif // QT_CONFIG(tooltip)
        self.combo_EHPUnluckyWorstOf.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make a Selection", None))
#if QT_CONFIG(tooltip)
        self.label_igniteMode.setToolTip(QCoreApplication.translate("MainWindow", u"Sets the EHP calc to pretend its unlucky and reduce the effects of random events", None))
#endif // QT_CONFIG(tooltip)
        self.label_igniteMode.setText(QCoreApplication.translate("MainWindow", u"EHP calc unlucky:", None))
#if QT_CONFIG(tooltip)
        self.combo_igniteMode.setToolTip(QCoreApplication.translate("MainWindow", u"Sets the EHP calc to pretend its unlucky and reduce the effects of random events", None))
#endif // QT_CONFIG(tooltip)
        self.combo_igniteMode.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Make a Selection", None))
#if QT_CONFIG(tooltip)
        self.label_IgnoreJewelLimits.setToolTip(QCoreApplication.translate("MainWindow", u"Ignore the limits on jewels", None))
#endif // QT_CONFIG(tooltip)
        self.label_IgnoreJewelLimits.setText(QCoreApplication.translate("MainWindow", u"Ignore &Jewel Limits", None))
#if QT_CONFIG(tooltip)
        self.check_IgnoreJewelLimits.setToolTip(QCoreApplication.translate("MainWindow", u"Ignore the limits on jewels", None))
#endif // QT_CONFIG(tooltip)
        self.check_IgnoreJewelLimits.setText("")
        self.grpbox_SkillOptions.setTitle(QCoreApplication.translate("MainWindow", u"Skill Options", None))
        self.grpbox_Combat.setTitle(QCoreApplication.translate("MainWindow", u"When in Combat", None))
        self.label_PowerCharges.setText(QCoreApplication.translate("MainWindow", u"Do you use &Power Charges ?", None))
        self.check_PowerCharges.setText("")
        self.label_NumPowerCharges.setText(QCoreApplication.translate("MainWindow", u"# of Charges (if not maximum)", None))
        self.label_FrenzyCharges.setText(QCoreApplication.translate("MainWindow", u"Do you use &Frenzy Charges ?", None))
        self.check_FrenzyCharges.setText("")
        self.label_NumFrenzyCharges.setText(QCoreApplication.translate("MainWindow", u"# of Charges (if not maximum)", None))
        self.label_EnduranceCharges.setText(QCoreApplication.translate("MainWindow", u"Do you use &Endurance Charges ?", None))
        self.check_EnduranceCharges.setText("")
        self.label_NumEnduranceCharges.setText(QCoreApplication.translate("MainWindow", u"# of Charges (if not maximum)", None))
        self.label_SiphoningCharges.setText(QCoreApplication.translate("MainWindow", u"Do you use &Endurance Charges ?", None))
        self.check_SiphoningCharges.setText("")
        self.label_NumSiphoningCharges.setText(QCoreApplication.translate("MainWindow", u"# of Charges (if not maximum)", None))
        self.label_ChallengerCharges.setText(QCoreApplication.translate("MainWindow", u"Do you use &Endurance Charges ?", None))
        self.check_ChallengerCharges.setText("")
        self.label_NumChallengerCharges.setText(QCoreApplication.translate("MainWindow", u"# of Charges (if not maximum)", None))
        self.label_BlitzCharges.setText(QCoreApplication.translate("MainWindow", u"Do you use &Endurance Charges ?", None))
        self.check_BlitzCharges.setText("")
        self.label_NumBlitzCharges.setText(QCoreApplication.translate("MainWindow", u"# of Charges (if not maximum)", None))
        self.label_GhostCharges.setText(QCoreApplication.translate("MainWindow", u"Do you use &Endurance Charges ?", None))
        self.check_GhostCharges.setText("")
        self.label_NumGhostCharges.setText(QCoreApplication.translate("MainWindow", u"# of Charges (if not maximum)", None))
        self.grpbox_5.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.grpbox_EffectiveDPS.setTitle(QCoreApplication.translate("MainWindow", u"For Effective DPS", None))
        self.grpbox_CustomModifiers.setTitle(QCoreApplication.translate("MainWindow", u"Custom Modifiers", None))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_Config), QCoreApplication.translate("MainWindow", u"&Config", None))
        self.menu_Builds.setTitle(QCoreApplication.translate("MainWindow", u"&Builds", None))
        self.menu_Settings.setTitle(QCoreApplication.translate("MainWindow", u"&Settings", None))
        self.menu_Theme.setTitle(QCoreApplication.translate("MainWindow", u"Theme ...", None))
        self.toolbar_MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

